### ISSUE TITLE
Добавить возможность просмотра количества плюсов и минусов к комментарию

### ISSUE THREAD

**Issue by Murmurianez** [limonte/dear-habr#10]
У меня часто бывает что один и тот же комментарий переходит из зелёной зоны в красную и наоборот - хочется видеть количество одобряющих и не одобряющих людей. Допустим, показывать тултип при наведении на оценку.

**Comment by stackalloc** [comment]
Такая возможность уже давно доступна:
![image](https://cloud.githubusercontent.com/assets/11295661/20113028/b5234db0-a5ff-11e6-8d7b-ecf2ee390722.png)

**Comment by valmat** [comment]
![то что вы предлагаете](https://habrastorage.org/files/691/c21/7ad/691c217add87457db0cafebbef84d520.png)

**Comment by Murmurianez** [comment]
Отлично)

**Comment by alan008** [comment]
Такие тултипы не работают в мобильном браузере, вроде бы
