### ISSUE TITLE
Формулы в MarkDown теряют переносы строк

### ISSUE THREAD

**Issue by AngReload** [limonte/dear-habr#102]
Например, 
```
$$display$$D(x) = \begin{cases}
1, &\text{for $|x| \leq 0.5 $}, \\
15/4 -7|x| +3|x|^2, &\text{for $0.5 < |x| \leq 1.5$}, \\
0, &\text{otherwise}
\end{cases}$$display$$
```
предпросмотр в режиме редактора Html
![inhtml](https://user-images.githubusercontent.com/23273107/32034527-7e2e9b6a-ba2c-11e7-840f-b7cb796698a2.png)
и в md:
![inmd](https://user-images.githubusercontent.com/23273107/32034576-bc933bcc-ba2c-11e7-95f6-1e3db064c6ff.png)

**Comment by KvanTTT** [comment]
Вот незадача - формулы теряют, хотя не должны, а [обычный текст не теряет](https://github.com/limonte/dear-habr/issues/92), хотя должен.

**Comment by AngReload** [comment]
Это уже исправлено, может стоит закрыть вопрос?
