### ISSUE TITLE
Когда перехожу из RSS (Feedly) на смартфоне открывается десктопная версия вместо мобильной

### ISSUE THREAD

**Issue by raiym** [limonte/dear-habr#103]
Проблема наблюдается только с Хабром. Приходится добавлять `m.` перед адресом

При переходе на Гиктаймс открывается мобильная версия. 

Раньше все работало нормально, поведение изменилось примерно месяц назад.

**Comment by raiym** [comment]
проблема до сих пор присутствует

**Comment by zhovner** [comment]
Повторить проблему не получилось. Android 7 и актуальная версия feedly.

Записал скринкаст:
<a href="https://files.catbox.moe/wpsw8c.mp4"><img width="171" alt="Feedly RSS habr.com screencast" src="https://user-images.githubusercontent.com/774290/50897533-73262e80-141d-11e9-93df-76633f904b19.png"></a>

Видно, что редирект на `m.` поддомен происходит с основного. Полагаю, нужно разбираться почему он не происходит у вас. Может дело в user agent, разрешении экрана или еще чем-то?

**Comment by raiym** [comment]
@zhovner спасибо за ответ. 

Баг пофиксили, видимо с новой мобильной версией
