### ISSUE TITLE
Англоязычная версия habrahabr.ru

### ISSUE THREAD

**Issue by raiym** [limonte/dear-habr#106]
Есть ли в планах у команды TM открыть англоязычную версию habrahabr.ru и, возможно, geektimes.ru? Какой-нибудь habr.com =)

Ближайший конкурент medium, но он не только для разработчиков. 

Не зная, всех нюансов, идея кажется довольно перспективной.
Плюсы: 
- Для авторов это возможность поделиться опытом с англоязычной аудиторией, таким образом, помимо прочего обозначить себя на международном рынке. 
- Для ТМ привлечь западных корпоративных клиентов, получая, при этом больший доход. 
- Возможность сделать проект международным и даже стандартом индустрии (как сейчас в рунете).
- TBD

Минусы:
TBD

Наполнение: 
- Думаю, большое количество существующих статей захотят перевести сами авторы (возможно нанять профессиональных переводчиков для того чтобы редактировать перевод)
- Существующий контент будут переводить пользователи ради практики, рекламы своей работы и плюсов (как сейчас переводят с английского языка)
- Возможно станет стандартом готовить статьи на двух языках. 

Как вам идея?

**Comment by zhovner** [comment]
@raiym @limonte  можно закрывать

**Comment by KvanTTT** [comment]
Почему можно? Разве уже появилась англоязычная версия?

**Comment by zhovner** [comment]
@KvanTTT ну на домен habr.com как раз за этим переехали. И здесь обещают https://habr.com/company/tm/blog/93946/

По слухам в течение месяца должны выкатить английскую версию.

**Comment by KvanTTT** [comment]
По слухам должны были сделать еще осенью, а потом в декабре :)

**Comment by 1Boomburum** [comment]
FYI :) https://habr.com/ru/company/tm/blog/435764/

**Comment by zhovner** [comment]
@limonte  @raiym теперь точно можно закрывать
