### ISSUE TITLE
Отсутствует вариант «без подсветки» для блока кода

### ISSUE THREAD

**Issue by AngReload** [limonte/dear-habr#107]
При написании статьи или комментария доступна конструкция:
```
<source lang="nohighlight">
  print("Hello, World!")
</source>
```
или в markdown:
````
```nohighlight
  print("Hello, World!")
```
````
Для псевдокода или редких языков хотелось бы отключать подсветку синтаксиса. Так же иногда плохо подсвечиваются фрагменты кода.

Сейчас нет возможности отключить подсветку. Если кто-то пытается убрать «lang», оставить его пустым или прописать «nohighlight», то выбирается рандомный синтаксис подсветки, что видно по некоторым постам и комментариям.

Сделайте вариант без подсветки по умолчанию: так как лень рыться в длиннющем выборе ЯП, многие просто ставят что-то из начала списка, например подсветку 1С для JavaScript-кода.

**Comment by zhovner** [comment]
Зашел как раз чтобы написать об этом. Предлагаю, чтобы `<source>` без параметра `lang=` не подсвечивал код вообще. А то сейчас бессмысленная подсветка раздражает и отвлекает:

![image](https://user-images.githubusercontent.com/774290/47558703-6a44b700-d91c-11e8-8690-0def6ed0f3fd.png)

**Comment by daler-als** [comment]
@AngReload, @zhovner, в свежей версии HighlightJS, которую мы используем, [появился псевдоязык plaintext](https://github.com/highlightjs/highlight.js/commit/dfe7bac4efcb1e873f12d62aac3f608f7490ff00), который как раз не раскрашивает содержимое source. За это большое спасибо [Егору Рогову](https://github.com/egor-rogov).

Постараемся обновить библиотеку в ближайшую неделю — две.

**Comment by daler-als** [comment]
> Возможно ли будет его выбирать именно в случаях когда lang не указан?
Подумаем, спасибо за идею.

**Comment by daler-als** [comment]
Готово. Добавили значение plaintext. 

> Возможно ли будет его выбирать именно в случаях когда lang не указан?
Это сделаем, но чуть позже.

**Comment by zhovner** [comment]
Спасибо

**Comment by daler-als** [comment]
> Возможно ли будет его выбирать именно в случаях когда lang не указан?

Готово. 


@AngReload, если тут всё, закройте задачу, пожалуйста.

**Comment by zhovner** [comment]
@AngReload @limonte закройте таск пожалуйста.
