### ISSUE TITLE
Цикл статей как сущность первого класса

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [limonte/dear-habr#111]
Некоторые особо большие статьи разбиваются авторами на несколько постов. Насколько я понимаю (ибо давно не заходил на сайт под своей учётной записью), авторы таких статей вынуждены заниматься разбивкой и связыванием постов вручную, и это влечёт за собой следующие вопросы:

* Каким образом унифицировать внешний вид цикла статей для всех авторов?
* Как гарантировать, что все статьи, принадлежащие циклу, будут правильно связаны и в правильном порядке?
* Каким образом поставить закладку ко всему циклу, не прибегая в перелистыванию статей?

Все эти вопросы, скорее всего, могли бы решиться, если бы присутствовала поддержка цикла статей. Интерес также вызывает теоретическая возможность автоматического перевода уже опубликованных статей (хотя, насколько это было бы осуществимо -- непонятно). Может, плохо искал, но обсуждалось ли ранее? Или, может, уже существует такая поддержка, а я только проснулся?

**Comment by daler-als** [comment]
@lyubomyr-shaydariv, добрый день! 

Правильно ли понимаю, что вы говорите примерно о таком: https://bureau.ru/soviet/? (Надо кликнуть на таб «Подборки».)

Могли бы вы привести пару примеров таких циклов с Хабра?

**Comment by lyubomyr-shaydariv** [comment]
@daler-als , здравствуйте!

> Правильно ли понимаю, что вы говорите примерно о таком: https://bureau.ru/soviet/? (Надо кликнуть на таб «Подборки».)

Скорее всего, нет. Мне вкладка "Подборки" напоминает теги, т.е., не совсем то, что я имел в виду.

> Могли бы вы привести пару примеров таких циклов с Хабра?

Да, конечно. Держите:

* [Code review по-человечески (часть 2)](https://habr.com/post/342244/) -- Сначала не понятно: имеет ли в виду автор только перевод статьи №2 с оригинального источника, или это вторая по счёту статья из этого цикла. Чтобы это понять, нужно сначала прокрутить картинку с "котейкой" и вчитаться во второй абзац после и без того большой картинки (т.е., по крайней мере увидеть, что в нём есть ссылка на предыдущю статью). Это довольно сложно делать даже на большом экране, но и было бы куда сложнее на моём старом домашнем лэптопе.
* [Новогодние подарки, часть первая: Meltdown](https://habr.com/post/371153/) -- Здесь автор не поленился указать ссылки на следующие части, но уже в конце статьи (т.е., прокрутить нужно очень много). И это очень хорошо, что автор не забыл это сделать вообще (мог, например, оставить ссылку на первую статью во второй). Но, как по мне, "часть первая" и без скобок читается при беглом просмотре слегка сложнее, чем "(ч. 1)".
* [Как я парсил Хабр, часть 1: тренды](https://habr.com/post/346198/) -- Тут я даже не понял, есть ли вторая часть и была ли она опубликована, хотя название намекает на продолжение, но и не делает ничего больше.

Грубо говоря, может, "Хабр" мог бы как-то организовать такие статьи не то что в подборку статей по определённой тематике, а в как бы "убер-статью" одного автора, которая могла бы как-то сгруппировать его статьи, посвящённые одной теме, в одном месте. Честно говоря, не помню, чтобы я встречал что-то похожее где-то раньше. Также не уверен, насколько хорошо бы мог лечь в концепцию блога такой подход. Но меня просто не покидает такая мысль, потому что время от времени замечаю, что даже в своём RSS-агрегаторе могу пропустить какую-либо часть статьи и даже этого не заметить.

**Comment by daler-als** [comment]
Спасибо за пояснение! 

> Честно говоря, не помню, чтобы я встречал что-то похожее где-то раньше. Также не уверен, насколько хорошо бы мог лечь в концепцию блога такой подход.

По сути — это родственник блока «Похожие статьи», подобное есть на всех сайтах, где надо объединить по смыслу статьи: на Медузе и в Википедии, например. В общем, полезная вещь в хозяйстве. 

Боюсь давать каких-то обещаний по срокам, но это полезная идея — добавил в нашу копилку. Спасибо :−)

**Comment by FTOH** [comment]
Можно сделать как в этом блоге: https://tomassetti.me/getting-started-with-antlr-building-a-simple-expression-language/
Там все статьи цикла имеют общий текст в оранжевой рамке.

**Comment by lyubomyr-shaydariv** [comment]
Ещё пара минусов отсутствия поддержки цикла статей взят из https://habr.com/ru/post/348868/ :

* Как я понимаю:
  * автор вручную жирным выделяет текущую статью;
  * автор в каждой статье вручную указывает что это перевод.
* Первые четыре статьи ведут на habrahabr.ru, с которого редирект ведёт обратно на habr.com.
* Нет "линейной" навигации от первой статьи к последней, поэтому за чтением по порядку нужно следить самому (кстати, спасибо за фиолетовый a:visited -- это упрощает такой подход).
