### ISSUE TITLE
Убрать идиотскую систему получения разрешения на комментирование за статью. Дать возможность комментировать сразу после регистрации.

### ISSUE THREAD

**Issue by FlamesoFF** [limonte/dear-habr#118]
Убрать идиотскую систему получения разрешения на комментирование за статью. Дать возможность комментировать сразу после регистрации, как принято на большинстве интернет-ресурсов.
Нет никакой логики или пользы в подобных ограничениях.

**Comment by 1Boomburum** [comment]
В обозримом будущем такого изменения не планируется. Ограничение на комментирование для новых аккаунтов сделано с целью защиты от всякой нечисти — чтобы нельзя было хулиганить в комментариях сразу после регистрации.

**Comment by FlamesoFF** [comment]
@1Boomburum для этого можно было бы просто ограничить количество комментариев за определенное время, до набора определенного количества очков "кармы". 
Статьи писать не за чем.
