### ISSUE TITLE
Добавить возможность LaTeX форматирования при написании постов 

### ISSUE THREAD

**Issue by Mihip** [limonte/dear-habr#13]
Сабж.

**Comment by nesteruk** [comment]
Я уже давно просил у администрации. Не реагируют.

**Comment by bionicman** [comment]
Администрация услышала. Более чем ))

**Comment by parpalak** [comment]
Зато свободная ниша позволила мне сделать [редактор маркдауна и латеха](https://upmath.me/). Народ успешно пользуется :)

**Comment by nesteruk** [comment]
Я просто встроил то же самое в собственный редактор. И да tex2cms это хорошее начинание, ктстати а Хабр импортирует сторонние SVG на Habrastorage?

**Comment by dotzero** [comment]
Мы сделали специальный хак, именно от tex2cms мы импортируем svg. И мы помним о TeX, может не так как вы ожидаете, но реализация будет.

**Comment by nesteruk** [comment]
@dotzero вы бы пообщались с ЦА, просили у них чего они вообще хотят. а потом уже делали реализацию. ведь из этого можно сделать конфетку если подключить правильные пакеты

**Comment by dotzero** [comment]
@nesteruk у нас есть определенные технические ограничения и мы не всегда можем сделать именно то, что хочет ЦА. Но есть мы всегда готовы выслушать любые пожелания.

**Comment by nesteruk** [comment]
@dotzero ну, главное чтобы вы добавили все нужные пакеты, сделали определения для очевидных вещей вроде дифференциальной d (я замучался печатать `\;{\mathrm d}x`) а также позволили добавлять не только формулы но еще и картинки. еще было бы круто если бы как-то была решена проблема бейслайна - например, сейчас если вы добавите буквы x и y в текст -- они будут на разном уровне из-за align=middle. я правда не знаю как эту проблему решать.

еще есть большая проблема что работать с latex без wisiwyg - нереально. нужен live preview.

**Comment by parpalak** [comment]
@dotzero А в чем хак? SVG вроде и так не кешируется на habrastorage. И к tex.s2cms.ru запросы идут напрямую. Например, к настоящему моменту с https://habrahabr.ru/post/314820/ - больше четверти миллиона хитов.

Нагрузку на сервер это не создает, там nginx раздает статику напрямую.

**Comment by nesteruk** [comment]
@parpalak есть еще один неприятный момент: наверняка, для подготовки этого поста, я нагенерил кучу "мусорного" контента (неправильных формул), которые теперь лежат на сервере. или есть какая-то политика удаления?

**Comment by parpalak** [comment]
@nesteruk Политики удаления нет. Крутые парни файлы не удаляют :)

Два раза я очищал весь кеш. Это приходится делать либо из соображений безопасности, либо если некоторые файлы генерировались с ошибкой. Их потом не найдешь.

В последний раз сбрасывал после [этого коммита](https://github.com/parpalak/tex.s2cms.ru/commit/be18a18cf22f644545829583002ca0bb1ce62b86). С тех пор кеш вырос до 633 мегабайт. Перед очисткой он занимал несколько гигабайт. Это не проблема. Я думал, он будет занимать больше места.

Кстати, зачем в дифференциалах `\mathrm`? Я специально посмотрел в книгах - там d тоже курсивом. А вот `\,` набирать приходится, да. В принципе, я могу добавить алиас для дифференциала, [мне не трудно](https://github.com/parpalak/tex.s2cms.ru/blob/master/tpl/displayformula.php#L11).

**Comment by dotzero** [comment]
@nesteruk список пакетов будет похож на tex.s2cms.ru, за исключением xymatrix, tikzcd и некоторых других. Ориентируемся на mathjax.org и mathematica.stackexchange.com

@parpalak svg кешировалось только с tex.s2cms.ru, но видимо что-то отвалилось, проверим.

**Comment by parpalak** [comment]
@dotzero Не надо кешировать. Я выше написал, почему.

**Comment by nesteruk** [comment]
@parpalak про некурсивную d лучше всего почитать [тут](http://tex.stackexchange.com/questions/14821/whats-the-proper-way-to-typeset-a-differential-operator) - вообщем изобрели такой стандарт, но следовать ему или нет - это решение каждого. если будете делать - сделайте с `mathrm` вариант, чтобы удобно было.

**Comment by parpalak** [comment]
В русской типографской традиции дифференциал курсивный. Да и когда мы пишем на бумаге, не меняем наклон у d.

Пока не буду добавлять. Неясно, что делать с текущими формулами, которые могли содержать \d и закешировались. Надо подумать.

**Comment by nesteruk** [comment]
@parpalak а что такое `\d`? вроде стандарт для этого оператора `\dd`, хотя кому как. еще я думаю что было бы суперудобно ввести такие вещи как `\dx` и `\dy` что сэкономило бы кучу времени

**Comment by limonte** [comment]
https://habrahabr.ru/company/tm/blog/319600 :rocket: 

Этот тикет можно закрывать, я правильно понимаю?

**Comment by Mihip** [comment]
Именно так, ведь функция уже реализована.
