### ISSUE TITLE
Сделать визивиг

### ISSUE THREAD

**Issue by nin-jin** [limonte/dear-habr#19]
Чтобы можно было писать и сразу видеть результат. А не так, что ты сначала пишешь, потом открываешь превью, мотаешь до нужного места, читаешь, мотаешь обратно, редактируешь, снова открываешь превью. И так до бесконечности.

Как вариант - сплитскрин. Слева код, справа превью с автообновлением. Но лучше визивиг.

**Comment by dotzero** [comment]
Сейчас выкатили обновленный редактор. Это конечно не сплитскрин, но в данный момент у нас есть некоторые ограничения на бекенде, может в следующей итерации что-то поменяется.

**Comment by nin-jin** [comment]
Ну вы хоть позицию скроллинга сохраняйте, тогда хоть как-то можно будет использовать. Сейчас приходится через webstorm статьи писать - там есть плагин со сплитскрином и синхронизацией скролла между панелями.

**Comment by KvanTTT** [comment]
@nin-jin, поддерживаю - все равно не юзабельно. Я использую Visual Code при написании поста.

**Comment by limonte** [comment]
Попробовал новый редактор и всячески обращаю ваше внимание на комментарий @nin-jin

>  Ну вы хоть позицию скроллинга сохраняйте

Очень юзабельно для авторов будет сохранять позицию скроллинга таба "Просмотр". Сейчас приходится каждый раз скроллить вручную.

**Comment by v-sorokin** [comment]
касательно скролла, в ближайшее время добавим фичу.

**Comment by bitre** [comment]
Сохранение позиции скрола при переключении между "Редактор" / "Просмотр" добавили на прошлой неделе.

**Comment by KvanTTT** [comment]
Позиция скролла, кстати, рассчитывается неправильно: полагаю, что берется позиция в тексте, делится на количество всех позиций и умножается на количество позиций в отрендеренном тексте. А нужно рассчитывать первую строчку в исходнике, находить эту строку в отрендеренном тексте и сколлить на нее.

**Comment by Mithgol** [comment]
Я не против визивига только в том случае, если его можно будет отключать, предпочитая набирать исходный код.

**Comment by nin-jin** [comment]
@Mithgol лучший визивиг - правильная подсветка синтаксиса исходного кода.

**Comment by Mithgol** [comment]
@nin-jin Сделали на Гитхабе правильную подсветку синтаксиса исходного кода, зато теперь в их редакторе вставка, клавишами Shift+Ins совершаемая, из Файерфокса под Windows 7 x64 не работает.

Такие штуки в состав браузера не входят, а руками сделать их с первого раза так, чтобы всюду работало не криво — очень трудно.

**Comment by nin-jin** [comment]
@Mithgol `shift+ins` - стандартная комбинация же. А то, что они её сломали - ну не надо это ломать.

**Comment by limonte** [comment]
Думаю, что редактор значительно улучшен и этот тикет можно закрыть. Я открыл #69 в котором описана проблема со скроллом таба "Просмотр".
