### ISSUE TITLE
Возможность убирать и менять голос за комментарии

### ISSUE THREAD

**Issue by limonte** [limonte/dear-habr#2]
Я промахивался по мизерным стрелочкам голосования за комментарии столько раз, что не пересчитать. 

Сделайте возможность изменять голос за комментарии или убирать его, это же несложно, правда?

**Comment by Mingun** [comment]
Было бы полезно, но только не на все время, а на пару минут после оставления отметки, ИМХО, этого достаточно, чтобы осознать оплошность и исправить ее.

**Comment by m0sk1t** [comment]
Тоже промахиваюсь, а иногда бывает такое что человек сморозил глупость, ты его заминусовал, а в дальнейшем он либо исправляет свой комментарий, либо исправляется в следующем комментарии и ты понимаешь что он просто ошибся, но дело уже сделано...
