### ISSUE TITLE
Более строгое соблюдение правил публикации статей

### ISSUE THREAD

**Issue by ZZ87iFPcx2h7Y5VP** [limonte/dear-habr#21]
Я считаю, что следует сделать _сложнее_ слепой проход через эту страницу. По крайней мере для писателей-новичков. Ещё было бы неплохо всё-таки _следить_ за выполнением этих правил.

**Comment by limonte** [comment]
Очень мало конкретики в вашем предложении. Я закрою этот тикет, не стесняйтесь добавить информации по теме и переоткрыть его.
