### ISSUE TITLE
В какой момент закрывать тикет?

### ISSUE THREAD

**Issue by limonte** [limonte/dear-habr#25]
Появился первый кандидат за закрытие: #7

Нужна помощь коллективного разума - в какой момент нужно закрывать тикет?

- когда количество 👎 голосов больше, чем количество 👍 ?
- когда количество 👎 голосов в два раза больше, чем количество 👍 ?
- какой-то другой критерий?

**Comment by ZZ87iFPcx2h7Y5VP** [comment]
Тикет закрывается, когда он решён, либо когда решение невозможно. Второй вариант не катит, так как вся затея с этим "Обращением к хабру" как раз в том, что есть некая надежда, что тикеты будут хотя бы рассмотрены.
Решённым №7 тоже рано называть, так как обсуждение ещё идёт и новые идеи ещё появляются. Самый новый вариант решения был предложен всего 17 минут назад.

От отношения к тикету его статус никак не зависит.

**Comment by selivan** [comment]
ИМХО вообще не надо, пусть так и висит заголосованный вниз. Это ведь тоже выражение мнения сообщества.

**Comment by limonte** [comment]
Закрывать надо, иначе эта уютная книга пожеланий превратится в свалку. Тикеты не удаляются при закрытии (их вообще невозможно удалить), закрытые тикеты можно посмотреть тут: https://github.com/limonte/dear-habr/issues?q=is%3Aissue+is%3Aclosed

**Comment by ComodoHacker** [comment]
- Когда предложение реализовано
- Когда получен ответ от Администрации, что реализовано не будет.

Если за закрытые тикеты нельзя голосовать, то лучше не закрывать отвергнутые.

**Comment by limonte** [comment]
> Если за закрытые тикеты нельзя голосовать, то лучше не закрывать отвергнутые.

За закрытые тикеты голосовать можно.
