### ISSUE TITLE
Провести амнистию для старых пользователей, которые получили readonly за разовые нарушения

### ISSUE THREAD

**Issue by psihius** [limonte/dear-habr#28]
Собственно, сам сижу уже с 2012 года за разовое нарушение по незнанию - раздел "События" появился так же тихо и незаметно, как и пропал. Заблокировали через 2 минуты после публикации, даже не дав понять что пошло не так :(

Хотелось бы всё-же получить возможность комментировать и голосовать, т.к. писать статьи это не моё, а участвовать в дискуссиях и голосовать за посты всё-же хотелось бы. И да, у меня какой-то особый read only, т.к. я не могу комментировать даже с премодерацией.

**Comment by 1Boomburum** [comment]
"Read-only от природы" и "Read-only за нарушения" - это действительно два разных RO, но всё же из обоих вы можете выйти самостоятельно, приложив немного усилий. Да-да, написав пост в песочницу. Поверьте, это не сложно ) Но видимо, не очень-то вам это и нужно, раз с 2012 года сидите под санкциями :)

**Comment by psihius** [comment]
@1Boomburum а что делать, если писать на хабр мне нечего? Т.е. у меня обыденный вебдев, а что веб дева не касается, то ни на хабр, ни на гиктаймс собственно и не годится по тематике. Но у меня было достаточно много комментариев, плюсов по ним и какую-никакую, а положительную карму я имел (сейчас я даже не могу посмотреть ни комментарии свои, ни статистику, ни карму - всё скрыто). Т.е. моя полезность была не в написании статей, а в их обсуждении.
Да и из всего что я пробовал писать, на хабре в итоге остался только один пост - https://habrahabr.ru/post/94714/

**Comment by 1Boomburum** [comment]
Как показала моя практика, сделать интересный пост можно почти из чего угодно :) и вовсе необязательно зацикливаться только на деве и PHP - раздел "песочница" тому пример.
Что же касается амнистии - пару раз мы её проводили, но сейчас санкции настолько гуманные, что в ней особо нет необходимости - те, кто действительно хотят на Хабр, без проблем выходят из RO.

**Comment by psihius** [comment]
Насколько я помню, меня все амнистии обошли стороной из-за моего особенного RO :(

**Comment by limonte** [comment]
@psihius насколько я понимаю, тикет можно считать закрытым. Переоткройте если я не прав.
