### ISSUE TITLE
Убрать кастомные обработчики Alt+⇐ и Alt+⇒

### ISSUE THREAD

**Issue by limonte** [limonte/dear-habr#3]
Alt+⇐ и Alt+⇒ являюсь стандартными хоткеями для "Назад" и "Вперед"

Отбирать у пользователей нативное поведение браузера является дурным тоном.

Я еще как-то могу вас понять когда вы заменяете стандартные "Назад" и "Вперед" на "Предыдущая страница" и "Следущая страница" там, где это актуально (листание списка постов). Но просто вырубать "Назад" и "Вперед" на странице поста или на странице профиля это очень плохо. Не делайте так.

**Comment by noscript** [comment]
:+1: Писал в суппорт на протяжении нескольких недель, без ответа.

**Comment by zencd** [comment]
Жёстко, конечно... Alt+arrows нормально для macOS, а на Windows - Ctrl+arrows. Я для себя так делал.

**Comment by v-sorokin** [comment]
Есть два варианта, либо совсем убрать хоткей, либо переопределить его на более понятный. Первый вариант не пойдет, так как многие привыкли пользоваться навигацией по страницам при помощи сочетания клавиш, поэтому остается только переопределить его. Какие есть варианты?!

**Comment by limonte** [comment]
Есть еще один вариант который нужно сделать **asas** для начала, убрать хоткеи там где это бессмыссленно - страница юзернейма, страница поста и все остальные где эта навигация не используется.

**Comment by v-sorokin** [comment]
@limonte согласен, учтем, поправим!

**Comment by bitre** [comment]
Убрали обработчики Alt+⇐ и Alt+⇒.

**Comment by noscript** [comment]
Вот это круто. Не ожидал :)
