### ISSUE TITLE
Упрощение отправки сообщений об ошибках автору поста

### ISSUE THREAD

**Issue by hdfan2** [limonte/dear-habr#32]
Постоянно встречаются посты с одной-двумя (а то и больше) ошибками (грамматическими/синтаксическими/др.). Честно говоря, лень каждый раз создавать сообщение, думать, как его сформулировать (чтобы получмлось не слишком резко), как-то обозначать, где именно ошибка. А если их десяток-другой? Замучаешься писать. На всех нормальных сайтах уже давно есть удобный механизм "выделил/Ctrl+Enter/опционально дописал, что не так или как надо". И автор сразу видит это с привязкой к тексту. Очень, очень хочется.

**Comment by aliceklipper** [comment]
Имхо, для этого лучше подходит механизм, используемый на [qiita](http://qiita.com): пользователь создаёт приватный форк статьи, правит, присылает автору пуллреквест, автор смотрит дифф и, если всё хорошо, принимает реквест.

**Comment by limonte** [comment]
> Qiita is a technical knowledge sharing and collaboration platform ** for programmers.**

Не забывайте, что на Хабре не только девелоперы.

**Comment by extempl** [comment]
@aliceklipper это больше для более крупных уточнений подойдёт. Для опечаток ctrl+enter вроде удобнее будет. Заодно и авторы будут перепроверять ошибки вместо того чтоб выкидывать в паблик сырую статью и ждать пуллреквестов.

**Comment by ValdikSS** [comment]
@aliceklipper 
>пользователь создаёт приватный форк статьи, правит, присылает автору пуллреквест, автор смотрит дифф и, если всё хорошо, принимает реквест.

В случае с парой грамматических ошибок или описок, совершать такие действия будет еще ленивее, чем написать сообщение автору. CTRL+Enter куда удобнее.

**Comment by KvanTTT** [comment]
Можно сделать и как на stackoverflow: редактирует или принимает правки более привилегированный пользователь или модератор.

**Comment by daler-als** [comment]
Надеюсь, упростили: https://habr.com/en/company/tm/blog/442208/.
