### ISSUE TITLE
Карма должна стремиться к нулю со временем.

### ISSUE THREAD

**Issue by kpmy** [limonte/dear-habr#33]
Раз уж деанонимизации кармы не планируется, значит она должна быть подвержена влиянию времени. А то сейчас получается олигархия, кто-то когда-то написал пару статей и теперь только гадит неугодным.

Полная аналогия с [freigeld](https://ru.wikipedia.org/wiki/%D0%A1%D0%B2%D0%BE%D0%B1%D0%BE%D0%B4%D0%BD%D1%8B%D0%B5_%D0%B4%D0%B5%D0%BD%D1%8C%D0%B3%D0%B8), карма как средство динамической саморегуляции, обмена эмоциональными мнениями о личностях, а не как средство накопления мощи и становления олигархии. Хочешь кармы - пиши статьи. Я пишу статьи, а у меня +1/-1, а кто-то не пишет и имеет +50, ходит с плюсомётом наперевес.

UPD: конечно, орицательная карма тоже должна стремиться к нулю со временем. А то ведь поспоришь с олигархом, а потом всю жизнь в заключении.

**Comment by AnROme** [comment]
Можно сделать для кармы несколько полей значений
- автор
- комментатор
- просто хороший человек

Но это будет как-то мудрено

**Comment by akastargazer** [comment]
Карма как инструмент самоорганизации сообщества вполне нормальный концепт.

Анонимность оценок кармы как средство защиты оценщиков понятна.

Однако же есть ещё два фактора - дешевизна выставления оценки и, как правильно подметил автор, вневременной характер оценки.

То есть, оценка ставится без последствий для оценщика (он защищён) и навсегда. А ведь люди со временем меняются, сообщества тоже, превалирующие доктрины могут трансформироваться и так далее. Но этого механизм кармы не учитывает. Он слишком примитивный, подогнан под прагматику текущего момента.

Так что, наверное, автор прав - карма не должна быть гранитным надгробием.

**Comment by extempl** [comment]
Возможно минус должен оставлять отпечаток в карме минусящего? Как на SO, например. Я думаю, подобные предложения уже были.

**Comment by GreLI** [comment]
Мастхев для отрицательной кармы.

**Comment by tyomitch** [comment]
@kpmy полностью согласен, и предлагал это в #16 

Кроме уже перечисленных позитивных эффектов, затухание кармы сделает бессмысленным её "накопление впрок", также известное как кармадрочерство.

**Comment by dom1n1k** [comment]
Не должно быть так. Вы не понимаете сущность кармы.
Карма это не сумма заслуг (заслуги это рейтинг, и он как раз затухает, причем сейчас даже слишком быстро, по моему мнению), карма - это моё **отношение** к человеку. И если человек показал себя так, что я пометил его мудаком, я не передумаю через месяц. Точнее, я может быть и передумаю, но исключительно по какой-то весомой причине, а не автоматически потому что время вышло. И соответственно наоборот тоже.

**Comment by akastargazer** [comment]
>Не должно быть так. Вы не понимаете сущность кармы.

Вы только что приватизировали смысл кармы. Нигде в правилах хабра не указывается, как надо или не надо менять отношение к человеку. Ваше отношение - это только ваше отношение.

**Comment by kpmy** [comment]
@dom1n1k вы описали то, что и так все знают - карма используется для выяснения отношений. Со временем всё развивается в олигархию и одно единственное истинно верное мнение, а все остальные мудаки.

**Comment by tyomitch** [comment]
1. Если минус в карму (пусть даже за мудацкое поведение) будет разовым шлепком по рукам, а не каиновой печатью до скончания веков -- то этих минусов перестанут панически бояться новички, и карма будет эффективнее выполнять свою прямую функцию -- передачу ценностей сообщества новым членам.
1. Оценка отношения к человеку, полученная им вчера, в любом случае лучше характеризует поведение этого человека, чем оценка, полученная им год назад.

**Comment by dom1n1k** [comment]
> Вы только что попытались приватизировать смысл кармы. Нигде в правилах хабра не указывается

Ничего подобного. Это и в правилах указано, и просто из здравого смысла понятно.

> Помните главное: карма — это субъективное отношение каждого, кто за нее проголосовал, к вашему аккаунту.

https://habrahabr.ru/info/help/karma/

**Comment by akastargazer** [comment]
@dom1n1k Повторю - нигде в правилах хабра не указывается, на каком основании менять или не менять отношение к человеку. Хабр не заставляет вас менять отношение через месяц или через два, или потому что он мудак, или потому что мудак вы.

**Comment by kpmy** [comment]
Можно привести пример обычая "побиение камнями", как живую аналогию кармы. Или, например, каждый из сотни судей выносит справедливый приговор за хулиганство, в итоге набегает 100 лет тюрьмы. Много парадоксов, приводящих известно к чему. Покажите имена судей, введите апелляции. Чего это айтишники живут, как в средние века?

**Comment by dom1n1k** [comment]
Правильно, Хабр не заставляет, потому что это мое субъективное отношение. Я его сам могу поменять по своим субъективным причинам. Может через месяц, может через год, может никогда.
И именно потому, что это **мое** отношение, я хочу чтобы оно менялось только мной, а не само по себе.

**Comment by kpmy** [comment]
@dom1n1k зачем вы повторяете, что есть сейчас в теме про предполагаемое изменение?

**Comment by akastargazer** [comment]
>потому что это мое субъективное отношение. Я его сам могу поменять по своим субъективным причинам

Вот, я и говорю, что суть кармы состоит просто в выражении отношения к личности, а причины этого отношения никак не проявлены, ибо закрыты тьмой анонимности.

Дело как раз в том, что ваше отношение видно лишь вам изнутри. Снаружи никто не знает - ваше это отношение, или не ваше. И никто не знает, на чём основано ваше такое отношение. 

Может, вы критически мыслящий человек, 
А может, вы поддались стадному чувству. 
Может быть, у вас проблемы в личной жизни и вы самоутверждаетесь за счёт других. 
Может, вы реально защищаете хабр от очередного наркомана. 
А может, вы хабраолигарх, и ведёте клановые войны - собираете с друзьями тусовочку и давите всех, кто (условно) высказывается супротив божества нашего солнцеликого Маска Илона. В результате такого подвижничества, например, хабр оказывается заполнен лишь заказным или переводным контентом. Ну, я к примеру.

**Comment by tyomitch** [comment]
> Покажите имена судей, введите апелляции. Чего это айтишники живут, как в средние века?

"Чтобы проголосовать за карму @имярек, заполните заявление в трёх экземплярах, подпишите его у куратора тематического хаба, заплатите хабрапошлину, и отправьте всё это в ТМ заказным письмом. Ваше заявление будет рассмотрено в двадцатидневный срок, и может быть отвернуто, если модераторы ТМ сочтут ваш голос безосновательным."

Как-то так?

**Comment by tyomitch** [comment]
Для ясности: я **категорически** не хочу в комментариях к хабрастатьям натыкаться на обсуждения кармы, правомерности плюсов/минусов, "отводов судей" и "апелляций". Это ещё хуже выяснения личных отношений.

Поэтому предложение @kpmy мне очень нравится -- если плюсы и минусы будут автоматически обесцениваться со временем, то мотивация ко всему этому сутяжничеству исчезнет сама собой.

**Comment by dom1n1k** [comment]
> В результате такого подвижничества, например, хабр оказывается заполнен лишь заказным или переводным контентом.

Очень сомневаюсь в этой причинно-следственной связи.

Дело в том, что у меня уже несколько лет перед глазами проходит пример другого ресурса, с немного похожей историей. Там тоже есть своя система оценок, но очень важно отметить, что там они несут сугубо информационную функцию - то есть даже получив минусов, никаких реальных санкций юзер не получает. Ему просто как бы говорят - "ты не прав" или наоборот "ты молодец". Наказать может только модератор в ручном режиме за конкретные нарушения правил.

Так вот. Ресурс переживает спад по сравнению со своими золотыми годами: меньше активности, меньше интересного контента. И там регулярно стоит вот такой же плач Ярославны - мол, во всем виноваты плюсики и минусики. Мол, они угнетают, новички их боятся, вот раньше было и небо голубее, и прочее, и прочее. Хотя старожилам очевидно, что причины гораздо глубже.

А именно - контент не пишется, потому что и некому. Поколение энтузиастов, которое когда-то создало ресурс и которое искренне вкладывало душу - ушло. У кого-то новые интересы, кому-то просто надоело. А поколение новое в этом смысле как-то... менее продуктивно. Им либо лень делиться, либо просто нечем. Но конечно же, в этом виноваты плюсоминусы :) На самом деле это просто такое удобное воплощение врага, на которого можно свалить собственную немощь.

На Хабре мало крутых статей, потому что крутые спецы их не пишут. А почему не пишут? Неужели потому что минусика в карму боятся? Пфф... Нет, они просто не видят аудитории, которая способна дать мощный и интересный фидбек. Имхо, только ради этого крутые спецы готовы тратить свое дорогое время. И уж поверьте, если на сайт придет некто, кто напишет мегаофигенный материал - ему в первый же день насуют плюсов по самые помидоры. Да только где он? В песочнице 80% материалов это школотронская чушь.

**Comment by kpmy** [comment]
@tyomitch 
> Как-то так?

Когда любое чучелко может Вершитъ Сутьбэ Льюдей, в частности, мою или вашу, имеет смысл отнестись ко всяким важным кнопочкам серьёзнее.

**Comment by kpmy** [comment]
@dom1n1k вы похожи на старика, который не заметил, как вокруг всё поменялось. Мечетесь между объективной и субъективной стороной дела, то мудаков отмечаете, то ревностно следите за чистотой и качеством контента. А у накармованных в прошлом стариков скопилась вся карма, и вот они решают, кому быть, кому не быть. Админский скайпочат и вот это всё. То есть средневековье в чистом виде. Не забывайте, 2007-й не вернуть.

**Comment by tyomitch** [comment]
> Ресурс переживает спад по сравнению со своими золотыми годами: меньше активности, меньше интересного контента. И там регулярно стоит вот такой же плач Ярославны - мол, во всем виноваты плюсики и минусики. Мол, они угнетают, новички их боятся, вот раньше было и небо голубее, и прочее, и прочее. <...> Но конечно же, в этом виноваты плюсоминусы :) На самом деле это просто такое удобное воплощение врага, на которого можно свалить собственную немощь.

Я согласен, что страх перед минусующими -- это чисто психологический барьер для новичков.
Почему бы этот барьер не понизить?
От троллей и неадекватов защитит даже затухающая карма -- не станут они ждать по месяцу следующей возможности насрать.

**Comment by ComodoHacker** [comment]
Это уже реализовано (почти). Достаточно регулярно комментировать, высказывая свое мнение без стестения, и карма медленно ползет вниз. Единственное отличие, что предел находится несколько ниже нуля. А так —

> Хочешь кармы - пиши статьи.

**Comment by kotlerman** [comment]
@dom1n1k 
> На Хабре мало крутых статей, потому что крутые спецы их не пишут. А почему не пишут? Неужели потому что минусика в карму боятся? Пфф... Нет, они просто не видят аудитории, которая способна дать мощный и интересный фидбек. Имхо, только ради этого крутые спецы готовы тратить свое дорогое время. И уж поверьте, если на сайт придет некто, кто напишет мегаофигенный материал - ему в первый же день насуют плюсов по самые помидоры. Да только где он? В песочнице 80% материалов это школотронская чушь.

Сразу оговорю, что я не спец в какой-либо области. Но, мне кажется, сути дела это не меняет.
А суть вот в чем. Я иногда подумываю попробовать написать какую-нибудь статью. Пока не знаю какую, знаний маловато. Но, предположим, у меня есть материал. Напишу я статью. Но, действительно, для кого? Нет желания писать для людей, принципиально не способных уважать отличную от собственной точку зрения, еще и сливающих за нее карму. Вот только, я полагаю, довольно большое количество людей, как и я, сидит и молчит, представляя себе сообщество именно таким. Они даже не пытаются высказать свое мнение, ведь знают, что моментально карма может быть и, скорее всего, будет слита. Поэтому они не пишут комментариев. В результате, мы видим только часть сообщества, придерживающуюся мейнстрима. А, возможно, чуть ли не большинство их не поддерживает (и среди молчащих, вероятно, есть спецы, способные генерировать качественный контент). Только высказаться и повлиять возможности нет. Как граждане под диктатурой правящей элиты.
Мне ситуация видится именно такой.
P.S. Открыт для критики.

**Comment by tyomitch** [comment]
@kotlerman идеальная хабрастатья выражает факты, а не мнения. Мнениям место в комментариях. Но даже и там мне не очень интересно читать личное мнение "не спеца ни в какой области" -- независимо от того, совпадает оно с моим или нет.

**Comment by kotlerman** [comment]
@tyomitch 
Я имел в виду, что если я пишу статью, то мне важно, для кого я ее пишу. Про "не спеца ни в какой области" и "но, мне кажется, сути дела это не меняет" я специально сразу указал, дабы не возник пустой разговор на тему, "а ты, собственно, спец в какой области", который бы ушел в сторону от темы и того, что я пытался сказать. Но разговор все равно пошел в эту сторону.
Дело в том, что не важно, спец я или нет. Я пытался сказать, что на моем месте мог бы быть и спец, чьи статьи были бы весьма востребованы. Или, предположим, я и есть этот спец. Я лично мыслю в этой ситуации именно так, как описал ранее. Результат - статьи нет, причем не из-за того, что нет спеца.

**Comment by dom1n1k** [comment]
Не хочу никого обидеть, но обычно самые громкие стенания о неуважении альтернативных точек зрения исходят от аналогов фоменко и петриков (которых не пустили в "мейнстримную" науку, ая-яй). Это я сейчас не намекаю ни на кого лично, это общие многолетние впечатления.

Даже непопулярное мнение будет воспринято нормально, если оно подкреплено логичными и вескими аргументами. И наблюдал такое неоднократно в комментариях, и личный опыт имею. Даже в таких, казалось бы, огнеопасных темах как "windows vs linux". Была как-то большая дискуссия об этом, я активно поучаствовал, писал то что думаю, но никаких активных сливов не заметил. Или вот помню как человек жестко, но аргументированно критиковал Теслу - тоже нормально все было.

@kotlerman
У вас в рассуждениях есть большой пробел. Сначала:

> Я иногда подумываю попробовать написать какую-нибудь статью. Пока не знаю какую, знаний маловато.

И буквально через фразу:

> Нет желания писать для людей, принципиально не способных уважать отличную от собственной точку зрения, еще и сливающих за нее карму. Вот только, я полагаю, довольно большое количество людей, как и я, сидит и молчит, представляя себе сообщество именно таким. 

То есть вы ещё даже приблизительно не знаете, чему могли бы научить других - но уже заранее перекладываете вину на общество, которое не способно оценить ваши старания. Это подмена понятий! Не надо смешивать уважение частного мнения и неуважение некомпетентных материалов. Есть частное мнение, а есть объективная техническая истина.

И да, я за то, чтобы статьи писали специалисты и эксперты. Статьи в стиле "пацаны, я уже целую неделю как узнал про этот фреймворк и уже спешу поделиться открытиями с миром" лучше публиковать в личном бложике - но их, увы, довольно много.

P.S. Я признаю, что _отдельные_ злоупотребления кармой, конечно, имеют место. Но в общем и целом система вполне рабочая и не нужно её демонизировать.
P.P.S. Мне только непонятно, за каким чертом администрация ТМ запретила положительно голосовать за людей без публикаций, но разрешает голосовать отрицательно.

**Comment by tyomitch** [comment]
> Мне только непонятно, за каким чертом администрация ТМ запретила положительно голосовать за людей без публикаций, но разрешает голосовать отрицательно.

Уже давно как можно голосовать за них положительно; но (по очевидным причинам) нельзя поднять им карму выше +5, чтобы они сами не могли голосовать.

**Comment by kotlerman** [comment]
@dom1n1k 
ответ в комментарии, который над вашим. Если важно именно, что пример про меня, то прошу заменить все "я" в исходном комментарии на абстрактного "очень крутой спец". И еще раз подчеркну, я не утверждаю, что происходит именно так, как я описал. Лишь предложил рассмотреть такую возможность.

**Comment by tyomitch** [comment]
@kotlerman ну вот вам конкретный пример: самый удачный из моих хабрапостов -- [Они забыли Польшу!](https://geektimes.ru/post/105436/) -- написан в 2010 и набрал рейтинг +180.

Это перевод рассказа Рэймонда Чена про случай из истории разработки Windows. В нём нет _никакого_ моего личного мнения, и _никакого_ личного мнения автора -- просто пересказ истории. Чтобы его написать, не нужно было быть "очень крутым спецом" -- просто нужно было знать историю из первых рук. Чтобы его перевести, тем более не нужно было быть "очень крутым спецом".

Внимание, вопрос: кто вам мешает запостить аналогичный топик, не выражающий _ничью_ точку зрения, и набрать сотню-другую плюсиков?

**Comment by kotlerman** [comment]
@tyomitch согласен. Уверен, что качественный контент будет оценен по достоинству. Но есть 2 "но":
1) Если сразу не набрать значительную карму, то стоит потом только раз неудачный коммент оставить, и кармы - как ни бывало. Просто обидно будет. Вероятность такого исхода немала, и она вполне так может снизить мотивацию к написанию статьи. Можете возразить: "кто заставляет писать комментарии? Пишите статьи." Даже считая данный вариант (воздержаться от выражения своего мнения, если оно отличается от мнения большинства из любящих сливать карму) приемлемым, в таком случае переходим к пункту 2
2) Как я раньше и сказал, мне лично важно, для кого писать. Даже если я уверен, что конкретная статья будет оценена по достоинству, я ее не напишу для аудитории, для который нет желания писать. Вопрос в том, какова реальная аудитория? Может, она совсем не такая, какой выглядит. Судить об аудитории я могу только по комментариям. Вот только, мне кажется, те, кто пишут комментарии - это лишь некая отдельная группа. Возможно, значительная часть молчит по описанным ранее причинам.

**Comment by dom1n1k** [comment]
> Уже давно как можно голосовать за них положительно; но (по очевидным причинам) нельзя поднять им карму выше +5, чтобы они сами не могли голосовать.

Вот это я упустил как-то.
Но как по мне, это все равно не очень правильно. Сам факт написания статьи - не показатель, потому что можно написать капитанскую статью, которая будет иметь некоторый плюс по оценкам и околонулевую полезность. И наоборот, можно иметь ноль публикаций, но оставлять мегаполезные комментарии (которые, как мы знаем, зачастую полезнее статьи).
Мне кажется, есть небольшая прослойка очень крутых специалистов, у которых на большой и фундаментальный материал просто нет времени, а писать какую-то ерунду не позволяет гордость. А вот комментировать они периодически могут.
Впрочем, это уже несколько оффтоп.

**Comment by tyomitch** [comment]
@dom1n1k сам факт написания статьи -- это что-то типа "продвинутой капчи", чтобы не допустить на хабр толпы ботов, чьё единственное предназначение -- плюсовать друг друга.

И да, _написать капитанскую статью, которая будет иметь некоторый плюс по оценкам и околонулевую полезность_ -- ненамного сложнее, чем прочитать мутный текст на капче; так что "дополнительный барьер" крайне низкий. Но почему-то некоторые комментаторы, в том числе @kotlerman, не решаются даже на это.

**Comment by kpmy** [comment]
Все, кого не устраивает политика партии, могут огранизовать свою площадку для обсуждения, тогда вас заметят. 
Например, вот https://github.com/in-trance/in-trance.github.io открытая платформа, никаких проблем с альтернативными мнениями и анонимными минусами от украинцев и либералов. А то на словах у всех свобода и прочее, а на деле минусуют в основном старожилы-русофобы.

**Comment by limonte** [comment]
Поздравляю, @kpmy. Ты первый, кто получил бан на этом репозитории :)
