### ISSUE TITLE
Разрешить использование тэгов в комментариях всем и всегда

### ISSUE THREAD

**Issue by klimovdm** [limonte/dear-habr#36]
Сейчас для тех, у кого карма ниже определенного уровня, существует запрет на использование html тэгов в комментариях. Это - глупость. Какая разница, какая у человека карма? Зачем запрещать сделать ссылку - это ведь элементарное уважение к читающим - переход по клику, а не копипаст. Цитата. Картинка. И т.п.

**Comment by VladReshet** [comment]
Да, странно получается. Минусованный - комментатор, а страдают при чтении неформатированного текста - другие пользователи.

**Comment by extempl** [comment]
Если картинка/ссылка не несут в себе того, что должны были или являются неприемлемыми - сам комментарий попросту заминусуется - у нас же саморегулирующееся общество, разве нет?
Да, в таком случае, наверное, стоит картинку скрывать совсем под спойлер, если комментарий нахватал минусов.

**Comment by nin-jin** [comment]
Если комментарий неприемлем, то для этого существуют модераторы, жалобы, удаление и банхаммер. А минусы как правило показывают не согласие с автором.

**Comment by GreLI** [comment]
Открою секрет: на данный момент запрещены не все теги, а только оформления текста (курсив, полужирный), ссылки (в том числе прямой вставкой, что работало пару лет назад) и вставка изображений. Всякими `<blockqoute>`, `<source>` и `<code>` можно пользоваться.

**Comment by nin-jin** [comment]
Ну круто, а остальные нафига запрещать?

**Comment by GreLI** [comment]
¯\_(ツ)_/¯ ТМ  «любит» читателей.

**Comment by GreLI** [comment]
`¯\_(ツ)_/¯` ТМ так «любит» читателей.

**Comment by nin-jin** [comment]
Наверно по библии учились управлять людьми :-)

**Comment by VladReshet** [comment]
А в библии что-то о тегах и разметке говорится?))

**Comment by VladReshet** [comment]
А в библии что-то о тегах и разметке говорится?))

2016-11-09 13:05 GMT+02:00 nin-jin <notifications@github.com>:

**Comment by nin-jin** [comment]
Там говорится о всемогущем существе, которое творит лютую дичь.

**Comment by acuna-personal** [comment]
Денискин мне лично отвечал по этому поводу. Давным-давно были нередки случаи, когда заминусованные оставляли ссыли на видосы и как-то гадили шрифтами. Только вот времена упячки давно прошли, те тролли давно выросли, а новому поколению не до Хабра, а администрация все еще живет в прошлом.

**Comment by bitre** [comment]
Убрали это ограничение, теперь пользователи с минусовой кармой могут использовать теги в комментариях.

**Comment by klimovdm** [comment]
**СПАСИБО**!
