### ISSUE TITLE
Не скрывать комментарии заблокированных пользователей

### ISSUE THREAD

**Issue by AigizK** [limonte/dear-habr#38]
Если пользователя забанили, НЛО скрывает все сообщения. Хотя предыдущие сообщения пользователя могли быть ценными. Предлагаю в момент бана дать возможность модераторам просматривать список сообщений и отметить какие надо скрывать.

**Comment by nin-jin** [comment]
И статьи не удалять.

**Comment by GreLI** [comment]
Не понимаю, почему это не сделали изначально опциональным для модераторов. (Понятно, что это нужно на случай появления Чёрного властелина и т.п.)

**Comment by tyomitch** [comment]
Действительно, всегда поражался такой политике. Человек, может, десять лет писал годные адекватные статьи, а потом где-то в комментариях сорвался с цепи и схватил бан -- а в итоге сообщество лишается всего его многолетнего вклада.

**Comment by acuna-personal** [comment]
Думал речь идет о засерении, а имеется ввиду не скрытие, а куча пробелов в виде надписей "НЛО прилетело и всем навставляло". Надо бы в описании указать конкретику...

**Comment by acuna-personal** [comment]
@GreLI вы знаете, если собрать все меры, которыми Администрация поддерживает порядок, можно сделать вывод, что школота атакует ресурс тысячами в день, и она таким образом им усердно противостоит. Только вот одно "но": время школотоы ушло еще со времен 2006, когда я еще в школе учился, а они все еще еще Черного Властелина ждут. Ну-ну...

**Comment by GreLI** [comment]
@acuna-personal, так анально огородили, никто и не пишет, включая школоту. Хотя иногда, благодаря НЛО школота проходит с детскими постами.

**Comment by ComodoHacker** [comment]
Если не ошибаюсь, перевод в read-only — более мягкая форма бана — не скрывает сообщений. Так что выьор у модераторов есть и сейчас.

> просматривать список сообщений и отметить какие надо скрывать
Вы же понимаете, что никто этого делать не будет.

**Comment by IRainman** [comment]
Куча плашек "НЛО прилетело и смысл ветки теперь потерян навсегда" была существенной причиной почему я перестал активно читать Хабр.

**Comment by 1Boomburum** [comment]
Объясняю, почему эта задача не будет реализована. 

Мы максимально лояльны к пользователям — если в комментариях появляется какое-то нарушение (кто-то ругнулся матом или вставил что-то неприличное), то мы обычно исправляем нарушение и связываемся с пользователем. Реже — накладываем санкцию в виде режима ReadOnly (из которого пользователь всегда может выйти самостоятельно). Удаление комментариев — максимально редкое явление, которое в большинстве случаев является следствием того, что обиженный (на санкцию) пользователь просит удалить его учётную запись и все его записи/комментарии. Если там есть что-то ценное, то мы пытаемся отговорить пользователя. Но если он нацелен удалить аккаунт, то никакие "дать модераторам возможность оставить что-то" тут не применимы. 

Говоря проще, не стоит переживать, что вы упускаете что-то важное.

**Comment by IRainman** [comment]
> Говоря проще, не стоит переживать, что вы упускаете что-то важное.
OK, собственно я так и подумал и перестал регулярно читать Хабр.
