### ISSUE TITLE
Сделать аудиоподкасты

### ISSUE THREAD

**Issue by Jaf4** [limonte/dear-habr#39]
Чтобы можно было послушать по дороге.  
Лучше еженедельные.

**Comment by limonte** [comment]
Оффтоп, как по мне.

**Comment by 1Boomburum** [comment]
Раньше был тип поста "Подкаст" - он был не очень популярен, там было много рекламы и мы его выпилили.

**Comment by limonte** [comment]
Закрываю этот тикет по причине отсутствия поддержки сообщества.

**Comment by Jaf4** [comment]
За четыре часа вы приняли решение об отсутствии поддержки? 
Ну ладн., удачи.

**Comment by acuna-personal** [comment]
@Jaf4 нет, Бумбурум ясно написал, что ранее такой проект уже существовал, но бы не очень популярен, и его даже выпилили из-за большого количества рекламы. На основании этого @limonte закрыл этот тикет.
