### ISSUE TITLE
Воссоединить Habrahabr и Geektimes

### ISSUE THREAD

**Issue by limonte** [limonte/dear-habr#4]
Об этом слишком много сказано. Перестаньте прогибаться под законы РФ и верните нам наш уютный блог.

**Comment by Mihip** [comment]
Отнюдь. В таком случае Хабр превратится в поток нескончаемой несуразицы и каши. Нет уж, право слово, от разъединения ресурсов больше пользы, нежели чем вреда. Уж смиритесь с этим и примите, как есть.

**Comment by dom1n1k** [comment]
Уж если Мегамозг смог обратно влиться, то уж ГТ тем более сможет. Особенно после того, как придумали "потоки". ГТ породил бы 3-4 новых потока, что-то типа "Гаджеты", "Научпоп" и что там ещё есть.
Разделение с самого начала выглядело искусственным и надуманным и продолжает выглядеть таким сейчас.

**Comment by acuna-personal** [comment]
Внесу ко всему перечисленному выше и свои пять копеек: всем известно, что Хабр по сути ознаменовал свой пласт культуры, создав даже новые понятия и слова с приставкой "хабро-". "Получил инвайт на Хабр", "Написал статью на Хабре" и т. д. до сих пор звучит гордо и вызывает множество положительных эмоций у любых людей, так или иначе связанных с ИТ (и часто даже не совсем связанных).

Однако есть Хабр. А что это еще за Гиктаймс? Вот хочу написать я статью на Хабре, а по тематике она попадает на Гиктаймс. Как я скажу, "Вот статью на Гиктаймс написал, почитай". Что человек подумает это за Гиктаймс? Какой-то мелкий сайтень для гиков, где пишут статьи все, кому не попадя, параллельно со ссылочными постами для Сеопульта?

Ну а кому хочется видеть в ленте только то, что он хочет, не для этого ли придумали хабы? Подпишись/Отпишись от нужных, будет тебе своя собственная лента, зачем же из-за каждого Хаба по сути иметь отдельный сайт?

**Comment by 1Boomburum** [comment]
К сожалению (к счастью?), объединение этих двух ресурсов в обозримом будущем не планируется.

**Comment by limonte** [comment]
@1Boomburum 

> К сожалению (к счастью?)

К сожалению. К большому сожалению.

**Comment by acuna-personal** [comment]
А Вы, простите-с, что услышать хотели?)

**Comment by limonte** [comment]
В соответствии с [официальным комментарием](https://habrahabr.ru/post/314750/#comment_9900164), закрываю этот тикет. Можно продолжать добавлять сюда аргументированные комментарии по теме.
