### ISSUE TITLE
 Не показывать рекламу с определенного порога кармы

### ISSUE THREAD

**Issue by ikashnitsky** [limonte/dear-habr#44]
Учитывая соотношение авторов и читателей на ресурсе, по-моему, вполне можно дать такую привилегию тем, кто поддерживает жизнь ресурса написанием статей.

Любой автор, даже написавший всего 1 средненький пост на 10К просмотров и +10 уже отдал хабру больше, чем он способен дать просмотрами рекламы на хабре за всю оставшуюся жизнь (я не говорю сейчас обо всем, что он сам при этом приобрел; речь вообще о ситуации win-win)

**Comment by 1Boomburum** [comment]
У обладателей бейджей "Автор", "Звезда", "Легенда" и "Старожил" в настройках профиля есть чекбокс "Отключить рекламу на сайте".

**Comment by ikashnitsky** [comment]
Не знал. 

И все же, по-моему, можно распространить на всех авторов с более простого порога кармы (5 или 10).

**Comment by KostyaTretyak** [comment]
Думаю с кармой "-3" тоже можно было бы... неплохо было бы убирать рекламу. А там уже хто вообще расслабился, тоесть с кармой "-4" и меньше, вот тем можно и показать ту вашу рекламу.

**Comment by 1Boomburum** [comment]
Други, если карму смогут отключать все включая тех, кто с кармой -3, то кому вообще будет показываться реклама? Мы её отключаем только тем, кто реально заслужил - десятками крутых постов. И эти люди, как показывает практика, практически не пользуются опцией отключения рекламы.

**Comment by KostyaTretyak** [comment]
Это был стёб, я думал, что это очевидно =)

**Comment by ikashnitsky** [comment]
На [странице хабраюзеров](https://habrahabr.ru/users/) сейчас указано:
> Всего пользователей: 717 186
В одной из недавних статей видел, что число авторов (если не врет память) порядка 3К. 
Ежедневная аудитория 8М. 
Не вижу большого ущерба для администрации в отключении рекламы авторам?
Да и если посмотреть на на содержание рекламы, напрашивается мысль о том, что она рассчитана отнюдь не на авторов, а больше на заходящую публику.

**Comment by ikashnitsky** [comment]
@1Boomburum понимаете, любой автор, даже написавший всего 1 средненький пост на 10К просмотров и +10 уже отдал хабру больше, чем он способен дать просмотрами рекламы на хабре за всю оставшуюся жизнь (я не говорю сейчас обо всем, что он сам при этом приобрел; речь вообще о ситуации win-win).

**Comment by tyomitch** [comment]
> И эти люди, как показывает практика, практически не пользуются опцией отключения рекламы.

Потому что у них всё равно AdBlock? :-)

**Comment by 1Boomburum** [comment]
Уже есть - https://habr.com/company/tm/blog/345312/
