### ISSUE TITLE
Сделать возможность быстро указать автору на ошибку в посте

### ISSUE THREAD

**Issue by pav5000** [limonte/dear-habr#46]
Часто люди замечают ошибки в постах. От обычных опечаток до крупных фактологических ошибок. Сейчас принято писать про ошибки в личку. Очень хотелось бы иметь возможность выделить в посте текст и по нажатию, например, ctrl+enter зарепортить автору об ошибке, как это сделано в Orphus. Это могло бы поднять качество постов, а автору и читателям сделать удобнее возможность улучшить пост.

**Comment by 1Boomburum** [comment]
Мы как никто другой знаем об этой проблеме и хотим её решить, но постараемся решить её более круто и гиково, чем "CTRL+Enter" )

**Comment by tyomitch** [comment]
Дубль #32

**Comment by limonte** [comment]
> Мы как никто другой знаем об этой проблеме и хотим её решить, но постараемся решить её более круто и гиково, чем "CTRL+Enter" )

Вот эти выкрутасы сообществу ни к чему. Сделайте **обычный** CTRL+Enter или хотя-бы опишите вашу идею, чтобы ее можно было поктритиковать.

**Comment by limonte** [comment]
Дубликат #32
