### ISSUE TITLE
Поддержка маркдауна

### ISSUE THREAD

**Issue by GreLI** [limonte/dear-habr#48]
Добавить поддержку маркдауна, например, как на Гитхабе. Многим удобнее печатать простой текст чем возится с тегами и визивигом. Обязательно с окошком предпросмотра.

**Comment by aNNiMON** [comment]
Вроде есть же: [Habrahabr Flavored Markdown](https://habrahabr.ru/info/help/markdown/)

**Comment by GreLI** [comment]
Всё хорошо, но нету на Хабре такой галочки:
![habr-no-md](https://cloud.githubusercontent.com/assets/1467392/20136162/792b386a-a684-11e6-8a9b-d6cb22726137.png)

**Comment by extempl** [comment]
Видимо markdown тоже доступно не для всех, скорее всего по тем же правилам как и разметка.

**Comment by dotzero** [comment]
MD доступен любому с >= 0 кармы.

**Comment by GreLI** [comment]
В очередной раз убеждаемся, что Хабр не любит читателей.

**Comment by dotzero** [comment]
Если вы считаете что 80% посетителей имеют карму меньше 0, то вы видимо в какой-то альтернативной вселенной.

**Comment by limonte** [comment]
> Если вы считаете что 80% посетителей имеют карму меньше 0, то вы видимо в какой-то альтернативной вселенной.

@dotzero ваш предыдущий комментарий полон издевки и несодержателен от слова вообще. Так не надо обращаться со своими пользователями.

У вас же есть доступ к базе пользователей и гораздо полезнее для сообщества будет получить ответ в виде "Нет, вы не правы с 80%, 45.32% пользователей имеют карму меньше 0".

**Comment by GreLI** [comment]
> Если вы считаете что 80% юзеров имеют карму меньше 0, то вы видимо в какой-то альтернативной вселенной.

Всё просто. Минимум 80% не пишет постов просто по принципу Паретто. До недавнего времени карма могла изменяться только вниз и она изменялась при любой активности (читай: написании комментариев). Сейчас процесс смягчился, но по факту и сейчас без постов в основном минусуют. Безнадёжно снижающаяся карма — отличная мотивация для написания постов! (сарказм) А неработающее оформление и комментарии раз в час отлично стимулирует писать подробные комментарии со ссылками, чтобы была та самая ценная обратная связь!

**Comment by dotzero** [comment]
@limonte На данный момент из всех зарегистрированных пользователей, только у 2182 человек отрицательная карма. И у 23570 пользователей карма выше 0, остальные имеют карму равную нулю.

**Comment by extempl** [comment]
@dotzero брали ли вы в расчёт неактивных пользователей? Может из активных это как раз таки другое процентное соотношение? Читая комментарии я в трети случаев, как минимум, натыкаюсь на автора с минусовой кармой. Может она потому и в минусе, что человек комментирует.

**Comment by GreLI** [comment]
@dotzero это отписка, а не статистика. Сколько из них делали хоть один комментарий или публикацию в последний квартал? Сколько из них имеют вообще имеют публикацию? Какая динамика кармы у активных пользователей без публикаций за последние пару лет?

**Comment by bitre** [comment]
Добавили возможность для пользователей с минусовой кармой использовать теги в комментариях, как в html-разметке, так и в markdown.

**Comment by GreLI** [comment]
Здорово! Но на Гиктаймсе пока нет.

**Comment by bitre** [comment]
Теперь и на GT.
