### ISSUE TITLE
Добавить возможность голосования за пост в мобильной версии сайта

### ISSUE THREAD

**Issue by limonte** [limonte/dear-habr#53]
Мобильных хабраюзеров все больше с каждый днем!

**Comment by v-sorokin** [comment]
Закрываем последние баги и скоро выкатим на прод!

**Comment by 1Boomburum** [comment]
Виталя, теги не забудь закрыть.

**Comment by bitre** [comment]
Готово.

**Comment by limonte** [comment]
Для полного счастья не хватает https://github.com/limonte/dear-habr/issues/2

А так, отлично выглядит - не промахнешься :)
