### ISSUE TITLE
Отмена инвайтов

### ISSUE THREAD

**Issue by Yorko** [limonte/dear-habr#56]
Выдал одному типу инвайт по просьбе знакомого.
Приглашенный пропал. Больше так не буду делать.
Но отмену инвайтов хотелось бы предусмотреть.

**Comment by bitre** [comment]
Если приглашение ещё не было активировано, его можно отозвать, нажав на красный крестик:
https://habrastorage.org/files/98a/2e4/514/98a2e4514cde44c18f3e7c6ee463d0f8.jpg

**Comment by ComodoHacker** [comment]
В следующий раз давайте инвайт только тому, кого знаете.

**Comment by limonte** [comment]
> Выдал одному типу инвайт

Вы и ваша карма несете ответственность за "типов", которых вы приглашаете. Иногда случается что приглашенный сливается настолько эпично, что карма пригласителя тоже страдает.
