### ISSUE TITLE
Некорректное отображение даты регистрации юзернейма на /users

### ISSUE THREAD

**Issue by limonte** [limonte/dear-habr#58]
![](https://i.imgur.com/IIe7tYM.png)

Вместо "0 месяцев" должно быть "X недель" если X > 0, в противном случае "Y дней"

**Comment by bitre** [comment]
Сделали:
![image](https://habrastorage.org/files/9f5/7d4/42a/9f57d442a5904ed0b1033bca7d9e9206.jpg)
