### ISSUE TITLE
+1 хаб: урбанизм

### ISSUE THREAD

**Issue by Mithgol** [limonte/dear-habr#60]
Предлагаю устроить на Хабрахабре (а лучше — на Гиктаймсе, в силу меньшей околокомпьютерности этой темы) новый хаб, посвящённый вопросам более удобного градоустройства и обеспéчения более комфортной (удобной) жизни в городах — то есть тем вопросам, которые изучает урбанистика (наука об устройстве городов) и вокруг которых складывается урбанизм (общественное движение за улучшение городов).

В этом хабе можно было бы обсуждать устройство современных городов, в этом хабе можно было бы обсуждать и возможности улучшения градоустройства — как технического улучшения, так и организационного.

В числе блоггеров, давно и изобильно пишущих на эту тему во внехабрахабровской блогосфере, могут быть названы, в частности,

* [Шумский](http://proboknet.livejournal.com/) ([probok.net](http://probok.net/))

* [Егоров](http://monteklever.livejournal.com/) ([Лаборатория Удобный город](http://tverwiki.ru/))

* [Варламов](http://varlamov.ru/) (прежде всего, в его серии блогозаписей «[города России](http://varlamov.ru/tag/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0%20%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8)»)

* [Гершман](http://gre4ark.livejournal.com/)

* сообщество [Делайте ПРАВИЛЬНО!](https://vk.com/delaitepravilno)

А вот на сайте GeekTimes таких блоггеров заметить нельзя, если не приглядываться.

Если же приглядеться, то можно увидеть, что даже сейчас в хабе «[Транспорт будущего](http://geektimes.ru/hub/transport/all/)» на GeekTimes есть ужé, на самом деле, некоторые такие блогозаписи, которые посвящены более градоустройству, нежели транспорту. (Но и транспорту они также посвящены, понятное дело: в противном случае сейчас, когда урбанистического хаба ещё нет, им нечего было бы делать в хабе «Транспорт будущего» и вообще на GeekTimes.)

Прежде всего это те блогозаписи, которые посвящены не транспорту, а транспортной инфраструктуре городов и междугороднего пространства:

* [В Голландии начинают тестировать пластиковые автодороги](http://geektimes.ru/post/253512/)

* [Остановить потенциального убийцу](http://geektimes.ru/company/speclab/blog/252420/)

* [Преобразователь направления](http://geektimes.ru/post/249220/)

(После появления урбанистического хаба эти блогозаписи надо будет **добавить** туда.)

Кроме того, в том же хабе есть блогозаписи, ещё заметнее посвящённые градоустройству:

* [Японцы построят подводный город на 5 тысяч жителей за $26 миллиардов](http://geektimes.ru/post/241820/)

* [В Китае появилась выделенная дорожка для пользователей смартфонов](http://geektimes.ru/company/shopozzcom/blog/241560/)

(После появления профильного хаба их надо будет **переместить** туда.)

Я предлагаю для этого хаба название «**Урбанизм**» (а не «Урбанистика», например), поскольку желал бы видеть его рамки скорее более широкими (как у общественного движения), нежели более узкими (как у теоретизации). Название «Градоустройство» также сгодится.

Мне кажется, что отсутствие такого хаба довольно сильно мешает раскрывать темы градоустройства, смежные темам транспорта. В качестве примера итогов такого затруднения можно указать, например, что на сайте GeekTimes можно без труда найти ≈полдесятка блогозаписей о том, как можно подобрать или собрать электробайк, однако же нет ни одной блогозаписи о том, как должны быть устроены велодорожки и велополосы в городе.

Мне кажется также, что стремление затрагивать эту тему есть у авторов, но в силу отсутствия необходимого хаба принимает несколько неприглядную форму. Например, в последние несколько дней вижу появившимися блогозаписи Сергея Захарова «[Дизайн российских городов, где он?](https://habrahabr.ru/post/314310/)» и «[Первый частный город в России, быть или не быть?](https://habrahabr.ru/company/smartprogress/blog/315428/)», которые считаю также сильно пострадавшими от отсутствия профильного хаба: от безысходности Захаров засунул их на Хабрахабр в хаб «Читальный зал».

**Comment by skssxf** [comment]
Даже по транспорту на гиктаймсе статьям не хватает хардкорности или даже... рациональности. Есть гиковские статьи о струнном транспорте, о других экзотических примерах, а хочется видеть статьи с более трезвым подходом. В общем, не хватает серии о мифах в транспорте в частности и урбанистике вообще.
В принципе, в сфере урбанистики довольно много IT-тематики, железячных тем, биологии и здоровья гиков, которые входят в моду на гиктаймсе. Хаб был бы полезен.

**Comment by 1Boomburum** [comment]
Создал — https://geektimes.ru/hub/urban/
Если кто-то является автором поста по этой теме, не забудьте перенести пост.

**Comment by limonte** [comment]
@1Boomburum у вас должны быть права на закрытие/переоткрытие тикетов этого репозитория. Пользуйтесь ими когда это имеет смысл, например в этом случае.

**Comment by limonte** [comment]
Блочить комментирование необязательно, т.к. в данном случае нет бесполезной дискуссии или оскорблений. Я переоткрыл комментирование на случай если у кого-то возникнет необходимость добавить комментарий к теме.
