### ISSUE TITLE
Не работает автоматический вывод средств ППА

### ISSUE THREAD

**Issue by limonte** [limonte/dear-habr#66]
Включил автоматический вывод средств 17го ноября. Прошло две недели, ничего никуда не вывелось :( 

В FAQ вижу:

> так система сможет сама раз в месяц (до 15-го числа, следующего за отчетным периодом) пополнять ваш кошелек Webmoney

Закончился 1-й день месяца, следующего за отчетным периодом. Если я правильно понял FAQ, то выплата должна была быть сегодня.

**Comment by limonte** [comment]
@1Boomburum помогите мне пожалуйста с этим вопросом, ни здесь ни в техподдержке не могу получить ответ уже неделю :/

**Comment by limonte** [comment]
Получил ответ от техподдержки:

### Автоматический вывод средств происходит 15 числа месяца (иногда с задержкой в 2-3 дня).

limonte:
> Хм, в FAQ написано «до 15-го числа, следующего за отчетным периодом», т.е. если я правильно понимаю «до 15-го» === от 1-го до 15-го, а не именно 15-го.

техподдержка:
> Приносим извинения, это разработчики всё никак не заменят текст на более корректную формулировку. На практике, выплаты осуществляются раз в месяц (чтобы никого не забыть). Происходит это в районе 15 числа. В прошлом месяце еще и двухдневная задержка была из-за каких-то заморочек с бухгалтерией.

Мой вопрос решен, но было бы очень хорошо внести корректировки в текст на FAQ странице.

**Comment by 1Boomburum** [comment]
Подобные вопросы лучше решать через суппорт, нежели тут )

**Comment by limonte** [comment]
Почему? Никакой критичных данных здесь не опубликовано, только актуальная информация, которая кстати не совпадает с текущим FAQ, который нужно бы чуток поправить :) Я наверно не единственный у кого возник такой вопрос и правильный FAQ бы мне помог, хабраюзеры читают его перед тем как задавать вопросы саппорту.
