### ISSUE TITLE
Сторонняя площадка для обсуждения

### ISSUE THREAD

**Issue by kpmy** [limonte/dear-habr#68]
Так как никаких подвижек в ситуации с кармой и сломанной саморегуляцией не предвидится, возможно отток комментаторов сможет обратить внимание администрации на проблему.

Оттекать можно сюда https://github.com/in-trance/in-trance.github.io но можно и не сюда. Важна массовость мероприятия.

**Comment by limonte** [comment]
Первое предупреждение за лютый оффтопик.

**Comment by limonte** [comment]
Поздравляю, @kpmy. Ты первый, кто получил бан на этом репозитории :)
