### ISSUE TITLE
Удалить рекламу и полностью дефинансировать ресурс

### ISSUE THREAD

**Issue by nesteruk** [limonte/dear-habr#7]
Превратить Хабр в полностью некоммерческий проект, удалить платные подписки и рекламу.

**Comment by Mihip** [comment]
Категорически против. Кушать хочется всем, разве не так? :)

**Comment by nesteruk** [comment]
Конечно хочется, но маркетинг убил этот ресурс. Я к сожалению сам приложил к этому руку в свое время. Читать его сейчас нереально, реклама на рекламе, рекламой погоняет.

**Comment by Mihip** [comment]
Диво дивное! Простите, вы серьёзно? Вам доводится наблюдать ухудшение качества статей вследствие введения интенсивного (и даже не агрессивного) маркетинга?

**Comment by 8GmN3mjZ5HtJ8GvJ** [comment]
>  Mihip commented 10 minutes ago
> Категорически против. Кушать хочется всем и каждому (даже разработчикам сего IT-ресурса), не правда ли? :)

Пускай на работу пойдут. Не обязательно зарабатывать с хабра и его юзеров, особенно рекламой и пассивным сливом инфы о нас, пользователях.

**Comment by nesteruk** [comment]
Главная страница сейчас:

- GitHub
- Блог компании DataArt
- C++
- Блог компании RailsClub
- Блог компании Kickidler
- Блог компании MobileUp
- Блог компании ESET NOD32
- Управление разработкой
- Настройка Linux
- Блог компании GeekBrains

Итого, из 10 записей, 6 (60%) маркетинговые.

**Comment by Mihip** [comment]
> 8GmN3mjZ5HtJ8GvJ commented 2 minutes ago
> 
> Пускай на работу пойдут. Не обязательно зарабатывать с хабра и его юзеров, особенно рекламой и пассивным сливом инфы о нас, пользователях.

Несуразица какая-то. Не стоит забывать, что Хабрахабр — продукт, причём, продаваемый продукт (что логично). Сомневаюсь, что в будущем реклама куда-либо денется, она будет присутствовать на ресурсе всегда, пусть и в различных её обличениях.

**Comment by Mak-Di** [comment]
@nesteruk Никто не запрещает фильтровать контент

**Comment by 8GmN3mjZ5HtJ8GvJ** [comment]
>  Mihip commented 4 minutes ago 
> Несуразица какая-то.

Что несуразного? По моему это очень логично, что альтернативный способ заработать деньги это пойти на работу. Вряд ли пользователи будут недовольны этим. А текущей ситуацией недовольны. 1:0.

**Comment by Archakov06** [comment]
Пока еще есть возможность пользовать AdBlock

**Comment by nesteruk** [comment]
> @nesteruk Никто не запрещает фильтровать контент

Если есть какой-то плагин для хрома который просто закрывает все "Блог компании Xxx", то поделитесь пожалуйста. На самом Хабре я такой возможности не нашел.

> Несуразица какая-то. Не стоит забывать, что Хабрахабр — продукт, причём, продаваемый продукт (что логично). Сомневаюсь, что в будущем реклама куда-либо денется, она будет присутствовать на ресурсе всегда, пусть и в различных её обличениях.

Сейчас он плохо продаваемый по причине того, что весь завален маркетингом. Как я писал выше, я тоже [приложил к этому руку](https://habrahabr.ru/users/mezastel/) и глубоко в этом раскаиваюсь -- конечно, очень радует что твой маркетинговый пост видят 5000 человек, но по сути я вместо интересных познавательных статей постил рекламные обзоры, которые помимо того что не уверен интересны они, еще обладают неприятным свойством моментально устаревать, т.к. выходит новая версия продукта и все старые посты уже нерелевантны.

> Это работает только для баннеров, а не для блога компаний.

**Comment by 8GmN3mjZ5HtJ8GvJ** [comment]
>  Archakov06 commented a minute ago 
> Пока еще есть возможность пользовать AdBlock

Возможность как таковая есть, но хабр (точнее, админы хабра) ноют и топают ногой, что им это не нравится. Плашку не видели чтоли? "Ну отключииииите адблоооокер 😭😭😭"

**Comment by Mihip** [comment]
> 8GmN3mjZ5HtJ8GvJ commented 36 seconds ago
> Что несуразного? По моему это очень логично, что альтернативный способ заработать деньги это пойти на работу. Вряд ли пользователи будут недовольны этим. А текущей ситуацией недовольны. 1:0.

И деньги для выплачивания гонораров за хорошие статьи они тоже, наверное, будут брать их своих карманов. :smile:

**Comment by nesteruk** [comment]
> И деньги для выплачивания гонораров за хорошие статьи они тоже, наверное, будут брать их своих карманов

Да никому не нужны эти деньги. Раньше писали качественные, интеренсые статьи, без всяких гонораров.

**Comment by Mihip** [comment]
> Да никому не нужны эти деньги. Раньше писали качественные, интеренсые статьи, без всяких гонораров.

Я Вас умоляю... Раньше и стимул у людей был для написания статей, все хотели поделиться своими познаниями, навыками, открытиями. Но ресурс слили в нуль. Большинство новичков не проходят дальше песочницы, годные статьи усыпаются минусами.

Друзья, мы занимаемся пустословием. Каждый из нас прекрасно понимает, что в первую очередь Хабрахабр есть бизнес, следовательно, не стоит даже надеяться на искоренение рекламы как таковой. Уж примите это так, как есть. Здесь мы бессильны (_до тех пор, пока с Хабра не начнут бесследно исчезать тысячи пользователей_).

**Comment by Koshiar** [comment]
@nesteruk Тогда как монетизировать? Если отвергаешь что-то, то предлагай решение.

**Comment by ZZ87iFPcx2h7Y5VP** [comment]
А кто сказал что хабр _обязан_ быть монетизирован? Вот прям обязан и точка!

**Comment by Koshiar** [comment]
Ребята, а кто за работу серверов и людей должен платить? Бесплатный в мире только воздух. И то скоро и его покупать будем.

**Comment by ZZ87iFPcx2h7Y5VP** [comment]
Создание ресурса это не базовое право человека, если что. Не хватает денег на поддержание проекта -- очень жаль, так случается иногда. Можно просить у инвесторов, как Twitter. Можно придумывать хитрые и невредимые для пользователя схемы монетизации как Reddit.
Можно быть жадными и класть на юзеров, как хабр. Хабр-то продаётся рекламодателям как дешевая потаскуха, да ещё и ноет если видит аблок у юзера.

**Comment by Mihip** [comment]
Друзья, что вы так взъелись из-за этой пресловутой рекламы?

**Comment by HGn7L4YxLBkbuGPe** [comment]
>  Mihip commented 3 minutes ago 
> Друзья, что вы так взъелись из-за этой пресловутой рекламы?

Из-за того, что:
1. хабр неразбочив в выборе рекламодателей
2. рекламы слишком много (если отключить адблок и проч.) и она в самых неожиданных местах
3. трекинг пользователей и слив инфы всем, кто заплатит

**Comment by Mihip** [comment]
Слив инфы о пользователях? Впервые слышу. А разве это не нарушает пользовательское соглашение?

**Comment by Koshiar** [comment]
А мне вот интересно, что я не так сказал? Люди не в курсе, как работает интернет? Есть компьютер, постоянно подключенный к интернету. На жестком диске лежит сайт. За обслуживание надо платить?
Надо. А размер диска ведь постоянно растёт как и нагрузка на сайт. 
А какой программист будет работать бесплатно?

Так твиттер как раз в убытке сидит. Статья: [http://www.cnews.ru/news/top/2016-03-01_ubytki_twitter_dostigli_2_mlrd_za_10_let_1]
Реддит я понял работает как и твитч.

Я не говорю, что за рекламу, но в современном мире приходится иногда с ней мириться.

**Comment by nesteruk** [comment]
Да не, вы все правильно сказали. Просто если посмотреть корпоративные рейты Хабра и взглянуть на статистику посещений (когда я замерял было 5-10тыс просмотров каждого поста, сейчас вроде бы меньше из-за спада), цифры совсем небольшие. Хабр никаким образом не потребляет несколько млн.руб. в месяц на хостинг.

Я не отрицаю базовую человеческую жадность, все хотят "миллион к 30", но Хабр был местом где можно было читать интеренсый пост, а сейчас он таким не является.

**Comment by KarelWintersky** [comment]
Ну введите уже платный вход на хабрахабр и успокойтесь :) Да, бесплатно - но с рекламой. За деньги - но без рекламы. Ну сколько там сделать... 300 рублей в месяц? Сколько посетителей оплатят? Тыщ пять наверняка. Ну вот уже полтора ляма в месяц. 

Я конечно не в курсе, какие аппетиты у команды разработчиков, но уж хостинг точно хватит оплатить :)

**Comment by andreikop** [comment]
Одним платным входом особо делу не поможешь. В мусорку из корпоративных постов и атрипрокрастинационно-мотивационных методик отпадает желание писать технические статьи. И пролистывать все это лень в поисках поста"Я вот тут запилил..."

**Comment by KarelWintersky** [comment]
В какой - в какой... в такой, когда обсуждение проблемы перерастает в ругань. Очевидно же :)

**Comment by 1Boomburum** [comment]
Хабр делают люди и НЛО, им нужно кушать, платить ипотеки итд, поэтому проект так или иначе должен зарабатывать деньги. На данный момент это медийная реклама (баннеры, которые вы все режете адблоком) и нативная реклама (корпоративные блоги) - потихоньку переходим от первого ко второму, но полностью отказываться от этого не будем.

**Comment by nesteruk** [comment]
Смотрите, все всё понимают, но у вас есть реальная проблема в том, что корпоративные блоги это на 95% шлак и это медленно убивает классный, в принципе, ресурс. Более того, если вы внимательно посмотрите, вы увидите что компании нагло злоупотребляют хабами, втаскивая в священну «разработку» то, что там вообще быть не должно. Вот например пост по  <https://habrahabr.ru/company/vasexperts/blog/313562/> DDoS: тут ни строчки кода, но компания решила добавить в «разработку», и никто ее оттуда не передвинул. Или например в блоге «программирование» пост <https://habrahabr.ru/company/1cloud/blog/314586/>  про то как вывести из себя программиста: это должно быть в каком-то уютном блоге «организиционная психология», или что-то вроде того.

**Comment by 1Boomburum** [comment]
"корпоративные блоги это на 95% шлак" - тут вы не правы в корне. Посмотрите топ постов за день-неделю-месяц (в течение пары месяцев) и увидите, что компании пишут очень крутой контент. Да, не у всех это получается, но и "Москва не сразу строилась" - мы обучаем их, правим посты, проводим семинары, консультируем итд, а откровенный шлак скрываем и отказываем в предоставлении услуг.

В остальном - вы путаете "потоки" и "хабы", а то, что часть хабов находится не в тех потоках - это мы со временем пересмотрим.

**Comment by limonte** [comment]
В соответствии с [официальным комментарием](https://habrahabr.ru/post/314750/#comment_9900164), закрываю этот тикет. Можно продолжать добавлять сюда аргументированные комментарии по теме.
