### ISSUE TITLE
Деанонимизация голосов за карму и комментарии, как в Disqus.

### ISSUE THREAD

**Issue by kpmy** [limonte/dear-habr#8]
Хотя, конечно, хабра-банды не одобрят деанонимизации, как же ещё гнобить неугодных.

**Comment by Mihip** [comment]
А вот здесь я категорически за, дабы неповадно было хабратроллям организовывать необоснованные страйки на мирных обывателей.

**Comment by 8GmN3mjZ5HtJ8GvJ** [comment]
Поддерживаю, но вы намеренно (я уверен вы это знаете) "нагрузили" вопрос / предложение дополнительной информацией. Это логическая ошибка`[0]` и используется в целях пропаганды или склонения к своему мнению. В общем - не очень честный приём.

`[0]: https://en.wikipedia.org/wiki/Loaded_question`

**Comment by kpmy** [comment]
Не очень честным является образование админских скайпочатов и осознанное извращение принципов работы механизма саморегуляции. А писать правду это не "нечестно". Может, кто не в курсе, зачем надо деанонимизировать голосования.

**Comment by 8GmN3mjZ5HtJ8GvJ** [comment]
>  kpmy commented 11 minutes ago 
> Не очень честным является образование админских скайпочатов и осознанное извращение принципов работы механизма саморегуляции.

У вас есть какие-нибудь данные? Как это происходит именно?

>  А писать правду это не "нечестно".

Бремя доказательства правды пока ещё на вас. И я не думаю что это универсальная правда, которую все с ходу примут. К тому же, нечестные деяния хабра не отменяют того, что ВЫ используете нечестные приёмы.

**Comment by dom1n1k** [comment]
Я против, потому что это смена правил игры задним числом.
Много лет люди ставили оценки, зная, что они анонимны.
А теперь предлагается им всем сказать - ребзя, мы передумали?

**Comment by Mihip** [comment]
> А теперь предлагается им всем сказать - ребзя, мы передумали?

Почему же? Авторов старых оценок оставить в тени, применить только к новым голосам, как вариант.

**Comment by 8GmN3mjZ5HtJ8GvJ** [comment]
А зачем это нужно, кстати? Чтоб предъявить тем кто минусовал?

**Comment by HGn7L4YxLBkbuGPe** [comment]
А, то есть ябедничать, а не только предъявлять.
Не могу поддержать, если цели такие... низкие.

Кстати, расскажите кто-нибудь о предыдущих случаях этих самых рейдов. Ну чтобы понимать, что они не выдуманы.

**Comment by kpmy** [comment]
Анонимные претензии в треде про деанонимизацию.

**Comment by loguntsov** [comment]
Предлагаю сделать только положительные голоса, так человек будет видеть кто его единомышленник. Это гораздо ценнее.

**Comment by Mihip** [comment]
Очень дельная мысль, между прочим!

**Comment by 1Boomburum** [comment]
Деанонимизация не планируется - есть немало примеров (та же лепра), где подобное приводит лишь к ненужным выяснениям отношений и карма-войнам, "ты мне - я тебе". Предложение "показывать только положительные голоса" в целом понравилось, но, к сожалению, тоже вряд ли будет реализовано.

**Comment by kpmy** [comment]
@1Boomburum а сейчас будто бы нет выяснения отношений, вообще не аргумент, люди срались и будут сраться, но то срач, полемика, а сейчас "тёмная" неизвестно от кого.

**Comment by tyomitch** [comment]
@kpmy как раз наоборот: когда фидбек анонимен, то это порождает полемику и обсуждение *мнений*, а не личностей участников.

**Comment by limonte** [comment]
В соответствии с [официальным комментарием](https://habrahabr.ru/post/314750/#comment_9900164), закрываю этот тикет. Можно продолжать добавлять сюда аргументированные комментарии по теме.

**Comment by kpmy** [comment]
@tyomitch ничего нельзя породить с одним комментарием в день, это так неочевидно?

**Comment by tyomitch** [comment]
@kpmy даже с одним комментарием в месяц можно вести полемику -- так вся классическая наука строилась. А вот срач с одним комментарием в день вести не получится.

**Comment by akastargazer** [comment]
>А вот срач с одним комментарием в день вести не получится.

Вы по-умолчанию считаете, что те, кого заминусовали, ведут срач (тем более, что именно на это намекают правила хабра - "минусуй гадких"). А это далеко не так.

**Comment by akastargazer** [comment]
Чем это место отличается от хабра, так это тем, что тут можно вести полемику и ты видишь реальное отношение к тебе. Реальное отношение, как в жизни - ты видишь, кто и как к тебе относится. Вот сейчас мой предыдущий камент получил отрицательную оценку, оппонент не согласен. Возможно, он даже приведёт какой-то аргумент. А может, и не приведёт. Но дискуссию можно продолжать в обычном режиме и потерять нить беседы за месяц ожидания уже невозможно.

Сравните это с хабром, где сидят чёткие анонимные пацанчики и не просто минусуют, а затыкают рот, не давая говорить. Называя это "борьбой за адекватность".

**Comment by tyomitch** [comment]
> Вот сейчас мой предыдущий камент получил отрицательную оценку, оппонент не согласен. Возможно, он даже приведёт какой-то аргумент. А может, и не приведёт.

Ваш предыдущий камент:

1. приписывает мне утверждение, которого я не утверждал;
1. приглашает меня оправдываться за это утверждение.

Естественно, что после такого камента я не собираюсь продолжать дискуссию.

**Comment by akastargazer** [comment]
>приписывает мне утверждение, которого я не утверждал;

Я не приписываю, я восстанавливаю ваши исходные посылки. Вы ведь не будете утверждать, что на хабре, как правило, минусуют за отклонения от линии партии? Предполагаю, что ваша позиция стоит на правилах хабра, которые гласят, что минусуют за гадкость.

**Comment by kpmy** [comment]
@tyomitch 

> даже с одним комментарием в месяц можно вести полемику 

Можно по форме или можно по существу дела? Сдаётся мне, что в 21-м веке заткнуть юзера на месяц равносильно убийству в период "становления классической науки".

**Comment by tyomitch** [comment]
Когда несколько человек интересуются мнением друг друга -- это дискуссия. Когда несколько человек пытаются навязать друг другу своё мнение -- это срач. Когда человек, не пытаясь выяснить чужое мнение, пытается выдать за него своё собственное _("Вы по-умолчанию считаете, что <...> я восстанавливаю ваши исходные посылки.")_  -- это демагогия.

Самое скверное, что заминусованные за демагогию потом идут всем жаловаться, мол они выражали непопулярную точку зрения и за неё поплатились кармой.

**Comment by kpmy** [comment]
Я могу высказать вам мнение, что ваши субъективные определения пока неверны, следовательно ваша оценка выражена в негативных терминах ошибочно, проще говоря - вы заблуждаетесь насчет демагогии или того, что вы подразумевали. Потом ваше такое заблуждение приводит к появлению несправедливых минусов.

**Comment by akastargazer** [comment]
>Самое скверное, что заминусованные за демагогию

Вы пока что ни разу не дали повод засомневаться в вашей позиции насчёт правил хабра, побуждающих минусовать гадость.

Однако же позволяете себе оскорблять собеседника, называя его высказывания демагогией.

Вы и вам подобные минусуете за гадость, так ведь? Вы же не затыкаете рот собеседнику за мнение, отличное от вашего, так ведь? Или всё же затыкаете и поэтому я не прав?

**Comment by tyomitch** [comment]
@akastargazer, [вы перестали бить свою жену?](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%B2%D0%BE%D0%BA%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81) Вы пока что ни разу не дали повод засомневаться в вашей позиции насчёт [правил хабра, побуждающих бить жён](https://en.wikipedia.org/wiki/False_attribution). [Вы же не начали вместо жены бить свою мать, так ведь?](https://ru.wikipedia.org/wiki/%D0%9B%D0%BE%D0%B6%D0%BD%D0%B0%D1%8F_%D0%B4%D0%B8%D0%BB%D0%B5%D0%BC%D0%BC%D0%B0) Спрошу прямо -- или всё же бьёте и поэтому я неправ?

**Comment by akastargazer** [comment]
@tyomitch, у вас логика расстегнулась. Ложная дилемма, она ведь про другое, к вашему несчастью. Изложу по-другому, чтоб вы таки поняли.

Хабр предлагает правило - минусовать за гадости. Вы согласны, что хабр предлагает минусовать за гадости?
Если да, то следующий вопрос - вы минусуете оппонентов?
Если да, то следующий вопрос - вы минусуете оппонентов по правилам хабра или по своим правилам?

Ну так что, осилите цепочку? Или рука чешется минусануть, да кнопки нет заткнуть рот оппоненту?

**Comment by tyomitch** [comment]
Нет, правила хабра не _побуждают_ минусовать за гадости. Правила хабра _предупреждают_, что за гадости вы можете огрести минусов -- но не призывают так делать, равно как и не призывают так не делать. Нету никаких "правил минусования" нигде, кроме как в вашей фантазии.

>Помните, что даже написав сотню самых полезных публикаций и искромётных комментариев, набрав +300 кармы, к примеру, вы можете потерять всё это с помощью одного глупого комментария не по теме или ещё какой гадости. Поэтому берегите себя и свою карму.

Для вашего "творческого переосмысления" цитат есть даже специальное название ["контекстомия"](https://en.wikipedia.org/wiki/Contextomy). Очень наглядная получилась демонстрация широкого набора демагогических приёмов в одном коротком треде :-)

**Comment by akastargazer** [comment]
>Нет, правила хабра не побуждают минусовать за гадости. Правила хабра предупреждают, что за гадости вы можете огрести минусов -- но не призывают так делать, равно как и не призывают так не делать.

Вы не чувствуете акцента на "минусовать за гадости".

Вы говорите, что правила предупреждают, что за гадости вы можете огрести. Другими словами, хабр говорит - "тут есть некая кнопочка, которую могут нажать".

По какой причине эту кнопочку нажмут?

Хабр называет эту причину, и эта причина - гадость (я условно обозначаю всё написанное на хабре одним словом "гадость", чтоб не цитировать сто раз одно и то же).

Чувствуете, что происходит? Лежит палка, кто-то может взять палку и огреть вас по голове за "гадости". Это механизм предоставленного сервиса, он так работает. Гадости тоже входят в этот механизм, иначе он работать не будет.
Понимаете ли, если никто не будет гадить, то и кнопка не будет нажиматься. Палкой никто никого не огреет. Должны быть "гадости", чтобы кнопка была нажата.

И тут мы приходим к главному вопросу - а что же такое эта гадость? И ответа, как ни странно, не получаем. Хабр оставляет ответ на усмотрение пользователя палки. Потому что "глупый комментарий" или "гадость" это не определение. Это эмоциональная оценка.

Следовательно, хабр предлагает не только палку, но и предлагает вам самому оценить своего собеседника - а не глуп ли он? Не говорит ли он вам гадости?

Манипуляция или побуждение тут вот в чём.

Если вы обнаружите в словах собеседника гадость, то это автоматически поставит вас в положение судьи, выносящего приговор. Если вы не нажмете кнопку, то ничего не произойдёт. А если же нажмёте, то это будет означать, что ваш собеседник сказал гадость. Так устроен хабр, его правила гласят - "за гадость огребают минусов". То есть, не хабр оценил, а лично вы оценили - гадость это или нет. Вы можете быть тупым как пробка, можете быть просто мудаком, можете быть с бодуна или иметь тяжкую дизлексию - это всё не имеет значения. Раз кнопка нажата, значит - это гадость.

Понимаете? От вас не требуется работы ума, от вас требуется лишь подтвердить наличие гадости. А это и есть манипуляция. Вот, кстати, о том же: https://habrahabr.ru/post/314750/#comment_9901516

Раз хабр даёт такой замечательный механизм оценки гадостей, то им нельзя не воспользоваться, когда собеседник говорит не то, что вы хотите от него услышать.

**Comment by tyomitch** [comment]
Когда вас при входе на стройку предупреждают надеть каску, чтобы в голову не прилетел кирпич -- вы такую же логическую цепочку строите? _"Там лежат кирпичи, и кто-то может взять кирпич и кинуть вам в голову, как о том предупреждают правила; значит, правила побуждают кидаться кирпичами; а раз есть такой замечательный механизм, то им нельзя не воспользоваться, когда коллега-строитель говорит не то, что вы хотите от него услышать. Значит, на стройке гнобят тех, кто выражает непопулярное мнение, караул!"_

**Comment by tyomitch** [comment]
Правила хабра разрешают выставлять оценку за гадость, разрешают выставлять оценку за красивые глаза на аватарке, разрешают выставлять оценку подбрасыванием монетки. Всё от слов _"Хабр называет эту причину, и эта причина - гадость"_ и до конца вашего предыдущего комента -- плод вашей фантазии, не основанный ни на чём.

**Comment by akastargazer** [comment]
>Правила хабра ... разрешают выставлять оценку за красивые глаза на аватарке, разрешают выставлять оценку подбрасыванием монетки. 

Процитируйте, где это написано. Иначе вы лжец.

**Comment by tyomitch** [comment]
См. выше:
> никаких "правил минусования" не существует нигде, кроме как в вашей фантазии.

Вместо того, чтобы найти и предъявить некие "правила минусования", требовать доказательства того, что их _действительно_ не существует -- это ещё один демагогический приём, см. ["Чайник Рассела"](https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D0%B9%D0%BD%D0%B8%D0%BA_%D0%A0%D0%B0%D1%81%D1%81%D0%B5%D0%BB%D0%B0).
Наверное, по мотивам этого треда потом напишу для ГТ статью "Demagoguery 101" :-)

**Comment by kpmy** [comment]
Про себя не забудьте упомянуть, ув. @tyomitch. А то ведь нечестно получится, не по существу дела. Вы же не планируете писать ложь и полуправду?

**Comment by akastargazer** [comment]
>Вместо того, чтобы найти и предъявить некие "правила минусования"

Хабр отчётливо предъявляет причины, по которым ставится минус. Вы это видите, но упорно не хотите признавать.
Приватизация смыслов и умение разговаривать свысока, усиливая свою точку зрения минусованием - признак настоящего хабраинтеллектуала.
Всего хорошего.

**Comment by tyomitch** [comment]
> признак настоящего хабраинтеллектуала.

А вот и демонстрация того, как скоро "свободная полемика без кармы и минусов" скатывается к [argumentum ad hominem](https://ru.wikipedia.org/wiki/Ad_hominem).

По сути спора: если **лично у вас** наличие в поле зрения минусовалки вызывает непреодолимое желание минусовать всех, кто _"говорит не то, что вы хотите от него услышать"_, и если **лично вы** во фразе _"Помните, что <...> вы можете потерять всё это с помощью одного глупого комментария не по теме или ещё какой гадости."_ видите правило _"Раз кнопка нажата, значит - это гадость."_ -- это ещё не основание переносить ваши личные комплексы на всех остальных.

Поберегите своё время, не отвечайте на этот комментарий. Тем более, что вы уже попрощались.

**Comment by kpmy** [comment]
Все, кого не устраивает политика партии, могут огранизовать свою площадку для обсуждения, тогда вас заметят.
Например, вот https://github.com/in-trance/in-trance.github.io открытая платформа, никаких проблем с альтернативными мнениями и анонимными минусами от украинцев и либералов. А то на словах у всех свобода и прочее, а на деле минусуют в основном старожилы-русофобы.

**Comment by limonte** [comment]
Поздравляю, @kpmy. Ты первый, кто получил бан на этом репозитории :)
