### ISSUE TITLE
Добавить ссылку на картинку в формате Markdown в habrastorage.org

### ISSUE THREAD

**Issue by KvanTTT** [limonte/dear-habr#88]
Хоть и мелочь, но приятно.

**Comment by 1Boomburum** [comment]
Совсем скоро выгрузим новый Habrastorage и там в числе прочих будет эта фишка.

**Comment by 1Boomburum** [comment]
Это сделали, проверяйте )

**Comment by KvanTTT** [comment]
Спасибо, работает!
