### ISSUE TITLE
Добавить возможность комментировать публикации старше 3 дней

### ISSUE THREAD

**Issue by andrey-pr** [limonte/dear-habr#9]

**Comment by valmat** [comment]
А сейчас разве так нельзя?

**Comment by Mihip** [comment]
Да, к сожалению.

**Comment by valmat** [comment]
@Mihip Вот например: https://habrahabr.ru/post/313686/#comment_9890064
Пост от 26 октября, комментарий от 2 ноября. Т.е. больше 3-х дней.

**Comment by 1Boomburum** [comment]
Такое ограничение наложено только на пользователей с правами Read&Comment — чтобы они могли принять участие в активной дискуссии, но не безобразничали в старых :) Проще всего в данном случае для таких пользователей - постараться добыть приглашение.

**Comment by heaviss** [comment]
@1Boomburum , а можно как-то увеличить это ограничение, до 5-7 дней, например? Читаю Хабр нерегулярно, уже несколько раз в пятницу хотелось задать вопрос автору понедельничной статьи, но нельзя.

**Comment by bopoh13** [comment]
Согласен с правилами (ограничение даёт +2 к воле). Листаю все статьи, иногда хочется вступить в полемику на тему недельной давности, - что смысла не имеет.

**Comment by 1Boomburum** [comment]
Заходите на Хабр чаще и перестанете замечать ограничение :) А вообще, как только прокачаете аккаунт до полноценного, проблема перестанет существовать.
И да, должны же быть хоть какие-то стимулы "расти на сайте", а вы хотите расслабиться - чтобы ничего не делая, когда зашёл тогда зашёл, где захотел, там накомментировал итд. Жаль, но нет :)

**Comment by bopoh13** [comment]
@1Boomburum не хочу я ничего на хабре прокачивать, мне WoT хватает :laughing: Меня всё устраивает!

**Comment by shalnoff** [comment]
я бы сказал, что это главное недоразумение сайта. Практика ограничения времени для возможности поставить оценку посту или комментарию напрямую связана с качеством контента всего сайта. Люди занятые и по объективным причинам посещающие Хабру и подобного рода сайта эпизодически или по приходящим раз в неделю или месяц дайджестам попросту лишаются возможности оценивать публикации и, тем самым, влиять на качество оных. В результате публикации в основном оцениваются людьми "зависимыми от онлайн-медиа", "школьниками" или попросту неадаптированными в современным информационным реалиям media-junkie. 

Логика этого ограничения понятна. По мнению условного маркетолога, такого рода практика должна стимулировать посещаемость сайта. В действительности же, как вы должно быть уже догадались, реально никому в голову не придет тратить время на отслеживание медиа только из-за желания поставить оценку (если только посетитель не является тем самым media-junkie). Профессионалы своего дела, кроме того что умеют делать свое дело хорошо, как правило, отличаются умением организовывать свое время. В этом смысле, подобного рода практика попросту способствует отсеиванию мнения людей в большей степени вовлеченных в предмет и ценящих своей время, и, одновременно, поощряет совсем другого рода публику. Что в результате сказывается на содержательном уровне сайта. 

Будьте благоразумны. Уберите это нелепое ограничение. Я лично не вижу никаких причин чтобы не сделать голосование без каких-либо ограничений по времени. Just Keep It Simple, Stupid, please.

**Comment by dom1n1k** [comment]
Не знал о таком ограничении, но действительно же 3 дня - это очень мало.
Желание оградить старые публикации понятно, но можно же сделать хотя бы 1-2 недели - в глобальной хронологии это всё равно мизер, но уже не создает проблем людям типа "уехал на выходные в деревню, вернулся, а тут хлоп, уже 3 дня прошли".

**Comment by bitre** [comment]
Изменили период комментирования для read-only и read & comment пользователей с 3 дней до 10.

**Comment by shalnoff** [comment]
Спасибо за внесенное изменение! Это безусловно радостная новость :) 

Однако, я бы, все же, на вашем месте убрал бы вовсе это ограничение. Зачастую ценность публикаций, которые нашли через поисковики или по старым ссылкам, прочли и оценили в разы более значима, нежели ценность сиюминутных "потоковых" новостей. 

В конечном итоге, как мне представляется, обсуждение старых но интересных и/или популярных публикаций может продолжаться очень долго. И в обсуждение могут включаться все новые и новые читатели.
