### ISSUE TITLE
Человекочитаемые названия картинок и относительные ссылки в статьях на них

### ISSUE THREAD

**Issue by KvanTTT** [limonte/dear-habr#93]
На GitHub можно создать папку, в которой будут храниться изображения, для которых можно использовать простые относительные ссылки в статье.

Старый формат:

```Markdown
![Common .NET & JavaScript GraphicsContext](https://habrastorage.org/storage2/89c/427/74c/89c42774cf90bdc873a0c34619cf7207.png)
```

Новый формат:

```Markdown
![Common .NET & JavaScript GraphicsContext](images/Common-NET-JavaScript-GraphicsContext.png)
```

Полный адрес к изображению будет такого формата:
```
https://habrahabr.ru/post/164439/images/Common-NET-JavaScript-GraphicsContext.png
```

Данная фича также позволит удалять картинки при необходимости и делать человекочитаемые имена.

Сами статьи, кстати, тоже могут быть доступны не только по числовому идентификатору, а по экранированному имени тоже.

**Comment by 1Boomburum** [comment]
К сожалению, это не получится сделать - все картинки хранятся на Хабрасторейдже с определённой структурой, мы не можем отдавать их с Хабра, равно как и "удаление картинок" противоречит текущему раскладу.
