### ISSUE TITLE
Когда захожу в профиль хабраюзера вижу сообщение "Вы ещё не добавили ни одной публикации в избранное."

### ISSUE THREAD

**Issue by raiym** [limonte/dear-habr#94]
![habr_bug](https://cloud.githubusercontent.com/assets/5698585/24405581/0f217ee0-13ce-11e7-89f9-c9b8582a276c.png)

Хотя должно быть "Пользователь (или %username%) ещё не добавил ни одной публикации в избранное."

**Comment by 1Boomburum** [comment]
Fixed :)
