### ISSUE TITLE
кнопки предыдущий/следующий непрочитанный коментарий

### ISSUE THREAD

**Issue by Katzen-Gott** [limonte/dear-habr#99]
Когда дискуссии в коментах становятся чуть менее активны, бывает сложно посмотреть все новые коментарии, ведь комментов так много. Почему бы не добавить к непрочитанным коментам кнопки для перехода к следующему и предыдущему непрочитанному коментарию.

**Comment by YemSalat** [comment]
<img width="63" alt="screen shot 2017-08-18 at 5 38 53 pm" src="https://user-images.githubusercontent.com/2361381/29463508-9237cf7c-843b-11e7-920d-28ab7c95547b.png">

Они ж и так вроде есть?

**Comment by Katzen-Gott** [comment]
после редизайна весь этот блок куда-то делся

**Comment by 1Boomburum** [comment]
Если ещё актуально, убедитесь, что стоит эта галка:

<img src="https://habrastorage.org/webt/mw/ju/90/mwju90htj6pb3k0sqw-pbfcyotm.png" />

**Comment by Katzen-Gott** [comment]
Ага, после установки галки появиись кнопки.
